### DISCUSSION TITLE
rabbitmq_auth_backend_http not sending vhost nor client_id anymore with v3.12.10

### DISCUSSION THREAD

**Discussion by headyj** [rabbitmq/rabbitmq-server#10192] [Other] [answered]
### Describe the bug

We are using vhost field for our authentication process, but this field is missing after the update from rabbitmq v3.11.18 to v3.12.10

### Reproduction steps

1. Install Rabbitmq v3.11.18
2. Configure rabbitmq_auth_backend_http
3. log the payload of rabbitmq_auth_backend_http somewhere, it will looks like this:
```
{"password":"****","vhost":"my-vhost","username":"my-username","client_id":"mqttjs_c5a43723"}
```
4. do the same using v3.12.10, payload is missing both vhost and client_id fields

### Expected behavior

payload should be the same between both versions

### Additional context

Rabbitmq installed on Kubernetes v1.27 using the [Operator](https://www.rabbitmq.com/kubernetes/operator/operator-overview.html)

Configuration
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: rabbitmq
  annotations:
    prometheus.io/probe: "false"
    prometheus.io/scheme: "https"
    rabbitmq.com/operator-connection-uri: https://rabbitmq.my-domain.io
spec:
  image: rabbitmq:3.11.18-management
  persistence:
    storage: 10Gi
    storageClassName: ebs-storage-class
  rabbitmq:
    additionalPlugins:
      - rabbitmq_web_mqtt
      - rabbitmq_auth_mechanism_ssl
      - rabbitmq_auth_backend_http
    additionalConfig: |
      vm_memory_high_watermark.relative = 0.7
      auth_backends.1           = internal
      auth_backends.2           = http
      auth_http.http_method     = post
      auth_http.user_path       = http://rabbitmq-auth-proxy-server.rabbitmq-auth-server.svc.cluster.local/auth/user
      auth_http.vhost_path      = http://rabbitmq-auth-proxy-server.rabbitmq-auth-server.svc.cluster.local/auth/vhost
      auth_http.resource_path   = http://rabbitmq-auth-proxy-server.rabbitmq-auth-server.svc.cluster.local/auth/resource
      auth_http.topic_path      = http://rabbitmq-auth-proxy-server.rabbitmq-auth-server.svc.cluster.local/auth/topic
      raft.wal_max_size_bytes   = 64000000
  replicas: 3
```
