### DISCUSSION TITLE
RabbitMQ container is stopped by macOS suspension and wake-up

### DISCUSSION THREAD

**Discussion by amills-vibeirl** [rabbitmq/rabbitmq-server#10221] [Other]
### Describe the bug

I have this docker-compose file below. Mongo and Redis always survive when I close my Macbook and reopen. But rabbit always dies. I am not sure if this is intended or not, but it's certainly not convenient for devs that end-up running things locally quite often. Is there a good reason why it always dies? Can't do a suspend? Obviously I don't know all the goings-on when the machine suspends, but I am curious.

```yaml
version: '3.9'

services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: "vibe-rabbitmq"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "5552:5552"
    environment:
      - RABBITMQ_PLUGINS=rabbitmq_stream,rabbitmq_stream_management
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

  mongo:
    image: mongo:6.0.12
    container_name: "vibe-mongo"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  rabbitmq_data:
```

any feedback appreciated, but seems like unintended behavior.

### Reproduction steps

1.  docker-compose up
2.  close macbook pro
3.  reopen macbook pro

mongo --> alive
redis --> alive
rabbit --> dead

### Expected behavior

expect rabbit to survive

### Additional context

n/a
