### DISCUSSION TITLE
PerfTest reports high latency

### DISCUSSION THREAD

**Discussion by skry-dev** [rabbitmq/rabbitmq-server#11026] [Questions]
Hi,

I did a performance test and saw high latencies in message flow.
End to end performance test latency goes up to 15 seconds. It shouldn't take more than a few seconds for me.
I checked resources and network but didn't find any anomaly.
How can I improvement message times?

My test command:

```
docker run -p 18691:8080  -it --rm --network perf-test rabbit:perftest \
    --uri amqps://<cluster_ip> -s 3000 -z60 --rate 500 \
    --quorum-queue --queue qq --queue-pattern 'perf-test-quorum-%d' \
    --queue-pattern-from 1  --queue-pattern-to 5 \
    --producers 100  --consumers 200  --metrics-prometheus \
    --metrics-tags type=publisher,type=consumer  -a --id "test 1"
```

My cluster properties:

I have 3 node RabbitMQ (version 3.12.12) cluster.
Rabbitmq run as docker container on each nodes.
Each node has 200GB Disk, 16CPU and 20GB RAM.
I used quorum queues.

<details><summary>rabbitmq.conf</summary>

```
listeners.ssl.default = 5671
loopback_users.guest = false
ssl_options.verify               = verify_peer
ssl_options.fail_if_no_peer_cert = false
ssl_options.cacertfile=***
ssl_options.certfile=***
ssl_options.keyfile=***
ssl_options.honor_cipher_order   = true
ssl_options.honor_ecc_order      = true

ssl_options.versions.1 = tlsv1.2
proxy_protocol=true

management.ssl.port       = 15671
management.ssl.cacertfile = ***
management.ssl.certfile   = ***
management.ssl.keyfile    = ***
management.ssl.honor_cipher_order   = true
management.ssl.honor_ecc_order      = true

prometheus.ssl.port       = 15691
prometheus.ssl.cacertfile = ***
prometheus.ssl.certfile   = ***
prometheus.ssl.keyfile    = ***

log.file.rotation.date = $D0
log.file.rotation.count = 6

cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
cluster_formation.classic_config.nodes.1 = rabbit@rabbit1
cluster_formation.classic_config.nodes.2 = rabbit@rabbit2
cluster_formation.classic_config.nodes.3 = rabbit@rabbit3

raft.wal_max_size_bytes = 1073741824
raft.segment_max_entries = 32768

message_interceptors.incoming.set_header_timestamp.overwrite = true

log.file = rabbit.log
log.dir = /var/log/rabbitmq
log.file.level = error
log.connection.level = error
log.channel.level = error
log.queue.level = error
log.mirroring.level = error

vm_memory_high_watermark.relative = 0.9
```
</details>

<details><summary>docker-compose.yml</summary>

```
version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:3.12.12-management
    container_name: rabbit
    hostname: rabbit1
    volumes:
      - /rabbit/volumes/certs:/etc/rabbitmq/certificates
      - /rabbit/volumes/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - /rabbit/volumes/advanced.config:/etc/rabbitmq/advanced.config
      - /rabbit/volumes/data:/var/lib/rabbitmq/mnesia/rabbit@rabbit1
      - /rabbit/volumes/erlang/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - /rabbit/volumes/logs:/var/log/rabbitmq
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "15672:15672"
      - "15671:15671"
      - "5672:5672"
      - "5671:5671"
      - "4369:4369"
      - "25672:25672"
      - "15692:15692"
      - "15691:15691"
    environment:
      - RABBITMQ_LOGS=/var/log/rabbitmq/rabbit.log
      - RABBITMQ_DISTRIBUTION_BUFFER_SIZE=384000
```
</details>

Test results:

```
test stopped (Reached time limit)
id: test 1, sending rate avg: 29535 msg/s
id: test 1, receiving rate avg: 27995 msg/s
id: test 1, consumer latency min/median/75th/95th/99th 555564/8634335/11241884/14891191/17180789 µs
```

Thank you.

### Expected behavior

I need improvement quorum queue performance.
