### DISCUSSION TITLE
How to change cluster_partition_handling in rabbitmq cluster deployed in kubernetes

### DISCUSSION THREAD

**Discussion by gagareg** [rabbitmq/rabbitmq-server#11083] [Questions] [answered]
Hello!

We use rabbitmq operator 3.6.6. I wanted to deploy the following cluster

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: range-rabbitmq
  namespace: default
spec:
  image: docker.io/bitnami/rabbitmq:3.9.10-debian-10-r5
  rabbitmq:
    envConfig: |
      RABBITMQ_MNESIA_DIR=/opt/bitnami/rabbitmq/.rabbitmq/mnesia/data
    additionalConfig: |
      cluster_partition_handling = autoheal
      log.default.level = debug
  replicas: 3
  resources:
    limits:
      cpu: 400m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 1Gi
```

The cluster is up and running but settings from additionalConfig are not applied.
```
I have no name!@range-rabbitmq-server-0:/$ cat /etc/rabbitmq/rabbitmq.conf
## Clustering
cluster_partition_handling = ignore

## Defaults
# During the first start, RabbitMQ will create a vhost and a user
# These config items control what gets created
default_permissions.configure = .*
default_permissions.read = .*
default_permissions.write = .*
default_vhost = /
default_user = user
default_pass = bitnami

## Networking
listeners.tcp.default = 5672

## Management
management.tcp.ip = 0.0.0.0
management.tcp.port = 15672

## Resource limits
# Set a free disk space limit relative to total available RAM
disk_free_limit.relative = 1.0
```

Why? And how to fix that?
