### DISCUSSION TITLE
Federation Requires local AND upstream Rabbit to have Federation Plugin enabled -> Breaking Change since 3.x

### DISCUSSION THREAD

**Discussion by BenniG82** [rabbitmq/rabbitmq-server#12893] [Other] [answered]
### Describe the bug

Since we upgraded our cental RabbitMQ from Version 3.x to Version 4.0.4 we are no longer able to setup a federation from our developer RabbitMQ-Instances to the central (upstream) RabbitMQ. 

All developer RabbitMQ-Instances are running with Federation Plugin enabled.
The central RabbitMQ does not have the Federation Plugin enabled.

With RabbitMQ 3.x as central RabbitMQ everything worked even with no Federation Plugin installed.

With RabbitMQ 4.0.4 we get the following error **on the satellites** in **Federation Status**:
```
{server_initiated_close,404,
                        <<"NOT_FOUND - no exchange 'federation: exchange.demo -> rabbit@7c1db11dd767 B' in vhost '/'">>}
```
![image](https://github.com/user-attachments/assets/73f3f2cc-3c2e-4294-adc6-d526d7776f26)

As you can see in the screenshot:
- Federation works for the connection with RabbitMQ 3.x with no plugins enabled **conn3-wo-plugins**
- Federation works for the connection with RabbitMQ 4.x with Federation Plugin enabled **conn4-with-plugins**
- Federation **does not work** for the connection with RabbitMQ 4.x with no Federation Plugin enabled **conn4-wo-plugins**

### Reproduction steps

# Use the following Docker-Compose file to setup:
- a satellite **rabbit** with RabbitMQ 4 with Federation Plugin enabled
- a upstream **upstream4WoPlugins** RabbitMQ 4.x with no Plugins enabled
- a upstream **upstream4WithPlugins** RabbitMQ 4.x with Federation Plugin enabled
- a upstream **upstream3WoPlugins** RabbitMQ 3.x with no Plugins enabled

docker-compose.yaml
```
services:

  rabbit:
    image: rabbitmq:4.0.4-management
    restart: always
    ports:
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"

  upstream4WoPlugins:
    image: rabbitmq:4.0.4-management
    restart: always
    ports:
      - "15674:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: guest

  upstream4WithPlugins:
    image: rabbitmq:4.0.4-management
    restart: always
    ports:
      - "15675:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"

  upstream3WoPlugins:
    image: rabbitmq:3.13-management
    restart: always
    ports:
      - "15676:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: guest
```

File: rabbitmq/enabled_plugins
```
[rabbitmq_federation, rabbitmq_federation_management].
```

# Execute the following commands for a demo setup
## Create Exchange exchange.demo in all RabbitMQ instances
```
docker compose exec rabbit rabbitmqadmin --base-uri=http://localhost:15672 --username=admin --password=guest --vhost=/ declare exchange name=exchange.demo type=fanout durable=true 
docker compose exec upstream4WoPlugins rabbitmqadmin --base-uri=http://localhost:15672 --username=admin --password=guest --vhost=/ declare exchange name=exchange.demo type=fanout durable=true
docker compose exec upstream4WithPlugins rabbitmqadmin --base-uri=http://localhost:15672 --username=admin --password=guest --vhost=/ declare exchange name=exchange.demo type=fanout durable=true
docker compose exec upstream3WoPlugins rabbitmqadmin --base-uri=http://localhost:15672 --username=admin --password=guest --vhost=/ declare exchange name=exchange.demo type=fanout durable=true
```

## Create Federation from **rabbit** (satellite) to **conn4-wo-plugins** (upstream 4.x with no plugins enabled)
```
docker compose exec rabbit rabbitmqctl set_parameter federation-upstream conn4-wo-plugins '{"uri":"amqp://admin:guest@upstream4WoPlugins:5672", "exchange": "exchange.demo"}'
docker compose exec rabbit rabbitmqctl set_policy federate4-wo-demo "^exchange.demo$" '{"federation-upstream-set":"all"}' --apply-to exchanges
```
**=> This federation does not work**

## Create Federation from **rabbit** (satellite) to **conn4-with-plugins** (upstream 4.x with Fed. Plugin)
```
docker compose exec rabbit rabbitmqctl set_parameter federation-upstream conn4-with-plugins '{"uri":"amqp://admin:guest@upstream4WithPlugins:5672", "exchange": "exchange.demo"}'
docker compose exec rabbit rabbitmqctl set_policy federate4-with-demo "^exchange.demo$" '{"federation-upstream-set":"all"}' --apply-to exchanges
```
=> This federation works

## Create Federation from **rabbit** (satellite) to **conn3-wo-plugins** (upstream 3.x with no plugins enabled)
```
docker compose exec rabbit rabbitmqctl set_parameter federation-upstream conn3-wo-plugins '{"uri":"amqp://admin:guest@upstream3WoPlugins:5672", "exchange": "exchange.demo"}'
docker compose exec rabbit rabbitmqctl set_policy federate3-wo-demo "^exchange.demo$" '{"federation-upstream-set":"all"}' --apply-to exchanges
```
=> This federation works

### Expected behavior

I expect Federation to work without additional plugins on the upsteam server.
This worked in 3.x
