### DISCUSSION TITLE
Please help us test the new Kubernetes peer discovery plugin!

### DISCUSSION THREAD

**Discussion by mkuratczyk** [rabbitmq/rabbitmq-server#13207] [Maintainer announcements]
We have merged a completely new k8s peer discovery mechanism and would appreciate your feedback. You can test it by simply deploying a cluster in the same way you currently do, using the `pivotalrabbitmq/rabbitmq:main-otp27` image. If you are using the [Operator](https://github.com/rabbitmq/cluster-operator), you can save this definition in a file and just `kubectl apply -f file.yaml`:

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: k8s-v2-test
spec:
  image: pivotalrabbitmq/rabbitmq:main-otp27
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 500m
      memory: 500Mi
  rabbitmq:
    additionalConfig: |
      log.console.level = debug
```

⚠️ This image is not meant for production use. After the test, just delete the cluster.

Once deployed, make sure that the cluster has 3 members (eg. by using `rabbitmqctl cluster_status`).

The new plugin is 100% backwards compatible, but works in a completely different way: `server-0` should always start without attempting to join any other nodes and all other nodes (pods with a higher ID) should join `server-0`. No Kubernetes API calls are made whatsoever.

If necessary, there's a few configuration options available, but for a vast majority of users, no configuration should be needed. Configuration options for the old version are ignored, so it's ok if it's still in the config file. More details in the [README](https://github.com/rabbitmq/rabbitmq-server/tree/main/deps/rabbitmq_peer_discovery_k8s).

If you do test it and it works, please leave a note as well, so that we know that someone tried. :)
We are especially interested in test in production-like environments which may have unusual networking configurations.

If it doesn't work for you - please share the logs from all nodes.
