### DISCUSSION TITLE
4.0.7: questions about disk and memory footprint of classic queues with larger messages

### DISCUSSION THREAD

**Discussion by ronmegini** [rabbitmq/rabbitmq-server#13225] [Other]
## **Environment Details**
- **Upgrade Path:** Upgraded from a **single-node RabbitMQ 3.11** to a **3-node cluster (v4.0.5)**.
- **Deployment Method:** Using **Bitnami Helm Chart v15.2.1** on Kubernetes v1.30.
- **Cluster Configuration:**
  - **Nodes:** 3 (each running RabbitMQ)
  - **Resources per Node:** 4 vCPU, 28 GiB memory, 250 GiB storage.
- **Workload:**
  - **Message Throughput:** ~400 messages/sec.
  - **Message Size:** ~0.5 MB per message.
  - **Queue Type:** Classic queues.
- **Other Clusters:** We operate multiple RabbitMQ clusters across different regions, **all with identical configurations and workloads**, but only this one exhibits the issue.

## Issue Observed
One of the RabbitMQ pods in the cluster is consuming **unexpectedly high memory and storage**, while other pods in the same cluster and across different environments do not exhibit this issue.

### **Potential Storage Leak**
- The total queue storage (message body size) **on the affected pod is ~90 GiB**.
- However, the **actual storage usage on the node has grown to 240 GiB**.
- **Question:** Where is the extra 150 GiB of storage consumption coming from?

<img width="300" alt="Image" src="https://github.com/user-attachments/assets/507db117-ea33-4e23-b3ba-752bfc5763cd" />
<img width="300" alt="Image" src="https://github.com/user-attachments/assets/b5e03819-fefc-4e3f-8e24-da64cc4e897a" />

### **Potential Memory Leak**
- **RabbitMQ Overview Dashboard reports** **15 GiB free memory**. (with 0.6 memory watermark)
- **However, Kubernetes metrics show only ~0.5 GiB free**.
- **Erlang Memory Allocators Dashboard** indicates RabbitMQ itself is using only **~1 GiB**.
- **Pod-level memory consumption is ~27 GiB** (far higher than expected).
- **Question:** Why is the pod consuming so much memory when RabbitMQ reports low usage?

<img width="600" alt="Image" src="https://github.com/user-attachments/assets/c381bf71-f6f7-4df9-969d-1f454bd2e4e5" />
<img width="300" alt="Image" src="https://github.com/user-attachments/assets/fad19b3a-f58f-40fb-8ba8-2b37f7a92ee5" />
<img width="300" alt="Image" src="https://github.com/user-attachments/assets/8be2de07-3526-44a3-a02a-05d5c7e2c471" />

## **Additional Observations**
- This issue **only affects one pod** in the cluster—**all other pods in the same cluster and in other regions are operating normally**. (potentially happen less significantly in one of the qa clusters)
- **All configurations** (memory settings, persistence, message TTL, etc.) are **identical** across clusters.
- **The workload is consistent** across all environments, making this behavior **unexpected**.
- The **affected pod eventually hits the storage watermark**, yet storage usage **continues increasing** until the node **crashes due to OOM (Out of Memory)**.
- After a restart, the **excess storage is cleared**, but the **high, unexplained memory and storage usage persist**—even though **RabbitMQ itself does not report abnormal resource consumption**.

### Reproduction steps

```
rabbitmq:
  global:
    security:
      allowInsecureImages: true

  image:
    registry: ***********.dkr.ecr.eu-central-1.amazonaws.com
    repository: rabbitmq
    tag: 4.0.5-debian-12-r0
  
  auth:
    username: admin
    existingPasswordSecret: rabbitmq-password-secret
    tls:
      enabled: true
      autoGenerated: false
      failIfNoPeerCert: false
      sslOptionsVerify: verify_none
      existingSecret: rabbitmq-amqp-cert
      existingSecretFullChain: true

  memoryHighWatermark:
    enabled: true
    type: "relative"
    value: 0.6

  clustering:
    enabled: true

  extraConfiguration: |-
    disk_free_limit.absolute = 10GB

  replicaCount: 3

  podAntiAffinityPreset: hard

  tolerations:
  - key: rabbitmq-on-demand
    operator: Exists
  
  resources:
    limits:
      memory: 28Gi
    requests:
      cpu: "4"
      memory: 28Gi

  persistence:
    enabled: true
    size: 250Gi

  service:
    portEnabled: false
    annotations:
      external-dns.alpha.kubernetes.io/hostname: amqp-int.prv.prod.ec1.cyner.io

  ingress:
    enabled: true
    hostname: rabbitmq.prv.prod.ec1.cyner.io

  metrics:
    enabled: true
    plugins: "rabbitmq_prometheus"
    serviceMonitor:
      enabled: true
      namespace: cross
      labels:
        release: kube-prometheus-stack
      default:
        enabled: true
      detailed:
        enabled: true
        family: [queue_metrics, queue_coarse_metrics, queue_delivery_metrics]
    prometheusRule:
      enabled: true
      namespace: cross
      labels:
        release: kube-prometheus-stack
```

## **Expected Behavior**
- Memory reported in RabbitMQ's dashboard should **match** actual pod memory usage.
- Storage usage should **not exceed** the total queue size unless justified (e.g., logs, persistence overhead).
