### DISCUSSION TITLE
Memory allocation spikes on first message published after hours of inactivity

### DISCUSSION THREAD

**Discussion by motmot80** [rabbitmq/rabbitmq-server#2785] [Other] [answered]
## Description ##
After 4-5 h of inactivity a tiny amount of published messages leads to a doubling the RAM usage.

## Reproduction ##
1. Fill up a cluster with 150 million messages to 50k queues (local non-lazy queues - 16 k queues each node) 
a) each node allocates about 14 GB of 32 GB RAM 
b) publish rates > 10 000 msg/sec fan out exchange are working fine and stable
c) Filled within 3 hours
2. **4-5 h of total inactivity** (no RAM churn visible)
3. Publish some messages f.e. about 50 (no fan out messages - only routed to a single queue)

## Expected ##
The cluster performs like 4 hours before using about the same amount of RAM (14 GB).

## Actual ##
Right after the first messages are published each cluster node allocates **another 15 GB RAM**!! within 5 minutes hitting the high-watermark.

## Log (Info level) ##
No log entries till the memory high watermark is hit.

## Rabbit MQ setup ##
**Rabbit MQ-Version**: 3.8.1 (Erlang 22.1.6)
**Nodes count**: 3 
**Node hardware**: 6 CPUs - 32 GB RAM each 

## Reproduction setup ##
|Type|Count|Description|
|---|---|---|
|Queues (lazy or non-lazy local )|50 000|16 666 per node|
|Messages ready|150 000 000|~ 14 GB RAM|

## System load before error ##
**CPU(user)**: < 10 %
**CPU(kernel)**: < 10 %
**RAM**: < 15 GB (~50 %)

## System load after "resuming" ##
**CPU(user)**: < 70 %
**CPU(kernel)**: < 15 %
**RAM**: < **30 GB** (~95 %)

**Comment by lukebakken** [comment]
Hello, and thanks for taking the time to report this.

Since it seems as though you can easily reproduce this behavior, could you please do so using the latest version of Erlang (23.2.3) and RabbitMQ? ([3.8.12-beta.1](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.12-beta.1)).

It would also be extremely helpful if you could export your cluster definitions to a file and attach them so we can see **exactly** how everything is set up. Thanks!

**Reply by motmot80** [reply]
![grafik](https://user-images.githubusercontent.com/1308503/106678406-f2fe3300-65ba-11eb-8803-9dfcb2819fe0.png)

We had a similar incident in production and reproduced the issue in our test environment with 3.8.11.

**Reply by motmot80** [reply]
Unfortunately it crashed after a while and we had to reset it, because of the extremly slow startup times. 
We'll try to reproduce the issue tomorrow exporting the definitions while the cluster ist running.

**Reply by michaelklishin** [reply]
Please use PerfTest to do so so that the exact settings (e.g. whether messages are published as persistent or not) is known https://rabbitmq.github.io/rabbitmq-perf-test/stable/htmlsingle/

**Reply by michaelklishin** [reply]
Total amount of memory used here is not particularly interesting, a breakdown over time (something that [Prometheus and Grafana dashboards support out of the box](https://www.rabbitmq.com/prometheus.html)) and [allocator tweaks](https://www.rabbitmq.com/runtime.html#allocators) would be significantly more relevant.

**Reply by motmot80** [reply]
Will an extract from https://grafana.com/grafana/dashboards/11350 be sufficient?  
We did no allocator tweaks yet.

**Reply by motmot80** [reply]
*> It would also be extremely helpful if you could export your cluster definitions to a file and attach them so we can see exactly how everything is set up. Thanks!*

We are filling the test environment right now to reproduce the issue, but actually `rabbitmq-admin export` doesn't seem to work. We'll try again when the message rampup is finished.

```
*** Error getting HTTP response:
...
version, status, reason = self._read_status()
  File "/usr/lib64/python2.6/httplib.py", line 397, in _read_status
    raise BadStatusLine(line)
BadStatusLine
```

Alternatively the clear text representation of our definition:

|Id|Type|Settings|Count|Description|Payload/Messages|
|---|---|---|---|---|---|
|1|Local Queue|queue-master-locator:client-local,max-length-bytes: 6291456, message-ttl: 604800000|65,000|**21,666 per node**|**30,000,000 messages**
|2|HA Queue|dead-letter-exchange:deadletter-XXX,ha-mode:exactly,ha-params:2, ha-promote-on-failure:always, ha-promote-on-shutdown:	when-synced|1||0 messages|
|5|Local Queue|dead-letter-exchange:deadletter-XXX, message-ttl:604800000|3||0 messages|
|4|Exchanges|Topic|21|Bound to 65,000 queues|**800,000 bindings** (routing-key)
|5|Exchanges|FanOut|5|Bound to local queues|1 bindings

**Comment by michaelklishin** [comment]
You can ask the node what [uses the memory](https://www.rabbitmq.com/memory-use.html).

**Reply by motmot80** [reply]
F.e. **rabbitmqctl** and **rabbitmq-diagnostic observer** unfortunately no longer worked.

**Reply by michaelklishin** [reply]
`observer` is intrusive and `rabbitmq-diagnostics memory_breakdown` is not (it queries runtime allocator stats once).

**Reply by motmot80** [reply]
Thanks for the information. We'll try this having reproduced the issue.

**Comment by motmot80** [comment]
We filled up the nodes again. Less but bigger messages (~40M)
We'll let it run for serveral hours.

## rabbitmq admin ui ##
![grafik](https://user-images.githubusercontent.com/1308503/106778395-394ca400-6646-11eb-825c-c35b9915d514.png)


## memory breakdown (node 1) ##
`rabbitmq-diagnostics memory_breakdown`

```
queue_procs: 6.8185 gb (43.28%)
allocated_unused: 3.0144 gb (19.14%)
mnesia: 2.1065 gb (13.37%)
msg_index: 1.7146 gb (10.88%)
plugins: 0.6976 gb (4.43%)
mgmt_db: 0.5675 gb (3.6%)
other_ets: 0.3485 gb (2.21%)
other_proc: 0.2705 gb (1.72%)
metrics: 0.0801 gb (0.51%)
other_system: 0.0622 gb (0.4%)
code: 0.0262 gb (0.17%)
connection_other: 0.0259 gb (0.16%)
binary: 0.0169 gb (0.11%)
connection_readers: 0.0018 gb (0.01%)
atom: 0.0016 gb (0.01%)
connection_channels: 0.0001 gb (0.0%)
quorum_ets: 0.0 gb (0.0%)
connection_writers: 0.0 gb (0.0%)
queue_slave_procs: 0.0 gb (0.0%)
quorum_queue_procs: 0.0 gb (0.0%)
reserved_unallocated: 0.0 gb (0.0%)
```

## erlang grafana memory board (node 1) ##
![grafik](https://user-images.githubusercontent.com/1308503/106778770-9cd6d180-6646-11eb-82d5-66cebe11947c.png)
![grafik](https://user-images.githubusercontent.com/1308503/106778824-a95b2a00-6646-11eb-809a-3b5788a53b82.png)
![grafik](https://user-images.githubusercontent.com/1308503/106778848-af510b00-6646-11eb-8df6-c65fa0d20da9.png)
![grafik](https://user-images.githubusercontent.com/1308503/106778867-b415bf00-6646-11eb-8642-4e32895974ee.png)

**Comment by motmot80** [comment]
![grafik](https://user-images.githubusercontent.com/1308503/106862682-bcfaa500-66c7-11eb-88ba-7cd1cb6e8204.png)

We were able to reproduce the issue after 4-8h of inactivity followed by publishing messages. During this resume "event" the RabbitMQ grafana memory statistics are showing that every RabbitMQ node "tries" to allocate almost 70 GB at peak level. The VMs have 32 GB RAM.

```
[Metric].Allocated Used: 66.76 GB
[Allocated by Allocator Type] eheap_alloc: 76.46 GB
[eheap_alloc]: Singleblock used: 60.76 GB
```

![grafik](https://user-images.githubusercontent.com/1308503/106863142-62ae1400-66c8-11eb-9980-8fb5ff75bf86.png)

As you can see there's not much going on till a smalll amount of messages are produced:

![grafik](https://user-images.githubusercontent.com/1308503/106866946-57111c00-66cd-11eb-862c-fa628f31880c.png)

Unfortunately we not only have a simulated testing issue with this. It already happened in production.

Any help would be greatly appreciated.
Thomas

**Reply by gerhard** [reply]
Thanks for sharing all these details, the last screenshots were particularly useful @motmot80.

The allocator growth stages are getting confused, this looks like an Erlang issue to me.

Being able to investigate this in a lab, as @michaelklishin & @lukebakken mentioned, will make a big difference. If we can reproduce this, then the Erlang team will be able to reproduce as well so that a fix can be identified, applied & tested. This is a good starting point (everything can be captured in a single file): https://github.com/rabbitmq/tgir/blob/master/s01/e07/k8s/rabbitmq/default-metrics.yml . [This](https://github.com/rabbitmq/tgir/blob/master/s01/e07/k8s/rabbitmq/perftest.help) & [this](https://rabbitmq.github.io/rabbitmq-perf-test/stable/htmlsingle/#simulating-high-loads) will help a lot with the PerfTest config. You may need more than 1 PerfTest instance to simulate this amount of load.

While we wait for the above, when a node is a in a bad state, the output for this command will go a long way: `rabbitmqctl eval 'recon_alloc:allocators().'`

**Reply by motmot80** [reply]
The memory management within the queue implementation seems to be very sophisticated and more or less different using lazy or default queues.

https://github.com/rabbitmq/rabbitmq-server/blob/52479099ecc9807097ad0af70b6c5d54cb5031e7/deps/rabbit/src/rabbit_variable_queue.erl#L2400

Simple reproduction setup:
1. Single Node with 20 GB RAM, Nvme M.2 Storage, 6 Cores (0.7 high watermark)
2. Load definition file with 800k bindings and 50k queues
3. Start publishing a message with 
`perftest --predeclared --exchange <BINDING-2-ALL-QUEUES> --routing-key <HIT-ALL-QUEUES> -f persistent --consumers 0 --producers 1 --slow-start --rate 1`

Using **LAZY** queues we are seeing RAM peaks publishing a single message to one exchange which fans out 50k queues.
The system freezes for a few minutes. Publishing some more messages one after another permanently rises this RAM peak and it doesn't immediatly stop on the high watermark. Pushing this a bit we can easily crash the process. Publish rate was max 1,000 msg/sec. Using the "normal" perftest without any further program arguments results in 20,000 msg/sec throughput on this deployment.

Using `rabbitmq-diagnostics maybe_stuck` when the system is in this state is showing serval thousands stuck (queue) processes:

```
2021-02-07 21:15:48 Found 43911 suspicious processes.
...<repeated>...
[{pid,<11325.1.4>},
                     {registered_name,[]},
                     {current_stacktrace,
                         [{gen,do_call,4,[{file,"gen.erl"},{line,208}]},
                          {gen_server,call,3,
                              [{file,"gen_server.erl"},{line,242}]},
                          {file,call,2,[{file,"file.erl"},{line,1540}]},
                          {rabbit_queue_index,get_journal_handle,1,
                              [{file,"src/rabbit_queue_index.erl"},
                               {line,887}]},
                          {rabbit_queue_index,publish,6,
                              [{file,"src/rabbit_queue_index.erl"},
                               {line,383}]},
                          {rabbit_variable_queue,maybe_write_index_to_disk,3,
                              [{file,"src/rabbit_variable_queue.erl"},
                               {line,1989}]},
                          {rabbit_variable_queue,publish1,7,
                              [{file,"src/rabbit_variable_queue.erl"},
                               {line,1824}]},
                          {rabbit_variable_queue,publish,6,
                              [{file,"src/rabbit_variable_queue.erl"},
                               {line,629}]}]},
                     {initial_call,{proc_lib,init_p,5}},
                     {message_queue_len,34},
                     {links,[<11325.0.4>]},
                     {monitors,[{process,<11325.59.0>}]},
                     {monitored_by,
                         [<11325.688.0>,<11325.692.0>,<11325.644.0>,
                          <11325.360.0>]},
                     {heap_size,4185}]
```

Why **LAZY** queues now: I thought lazy queues should behave more cautious with RAM allocation than default queues. So this is not exactly our **NON LAZY** queue issue after hours of inactivity. In this **NON LAZY** scenario there also was no big message fan out. But maybe both issues are related in our environment (high binding count f.e.).

**Reply by gerhard** [reply]
@motmot80 this is great, we have everything we need to start reproducing. Will update as soon as we have something.

This has also made it through to us (+@mkuratczyk) via the official channels, we are on top of it from both sides.

**Reply by motmot80** [reply]
Attached you'll find a simple synthetic example with 50k queues where you can use the exchange "TestExchange" with routing-key "route1" to publish fan out messages.

[50k-lazy.zip](https://github.com/rabbitmq/rabbitmq-server/files/5943367/50k-lazy.zip)

We imported the definitions with f.e.:

`{rabbitmq_management, [{load_definitions, '/etc/rabbitmq/definitions/50k-lazy.json'}]}`

**Reply by motmot80** [reply]
The full definition backups of our testing environment are attached to the official ticket.

**Reply by gerhard** [reply]
We will run a lazy and a non-lazy environment to see if it makes a difference. Both single-nodes (for now).

**Reply by gerhard** [reply]
We have deployed 1 node & imported 50k lazy queues. This is the exact config that we have used:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: vesc-1002
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: lazy
  namespace: vesc-1002
spec:
  replicas: 1
  image: rabbitmq:3.8.11-management
  resources:
    requests:
      cpu: 6
      memory: 20Gi
    limits:
      cpu: 6
      memory: 24Gi
  persistence:
    storageClassName: ssd
    storage: 100Gi
  rabbitmq:
    additionalConfig: |
      disk_free_limit.relative = 1.0
      vm_memory_high_watermark.relative = 0.7
      log.file.level = debug
```

The first problem that we are seeing is that the CPUs are maxed out due to queue metrics collection.

From the OS perspective:
<img width="1965" alt="Screenshot 2021-02-08 at 12 50 02" src="https://user-images.githubusercontent.com/3342/107222339-b1cbb000-6a0c-11eb-8483-1ce64e8c4c12.png">

From the Erlang perspective `rabbitmq-diagnostics observer` - `rr <ENTER>` - `10000 <ENTER>`
<img width="1970" alt="Screenshot 2021-02-08 at 12 46 57" src="https://user-images.githubusercontent.com/3342/107222361-b7c19100-6a0c-11eb-8b93-1dd31129ac92.png">

Before we go any further, we must change the default metrics configuration as the node is under intense CPU pressure and therefore not in a good shape to continue.

If you are curious about the metrics aspect, we have captured all relevant details here: [TGIR S01E07](https://www.youtube.com/watch?v=NWISW6AwpOE&list=PLfX-LA-Cf6rE16woOuRmi3goM_K8PUAhQ&index=3)

Once we have applied the necessary metrics changes, we will continue investigating.

**Reply by motmot80** [reply]
We know metrics aren't cheap. In our test and production environments we have about 25% CPU background noise because of this. We already did different optimizations gathering queues and bindings using `list_queues` and `list_bindings` every x minutes on one of the nodes. As far as I know we also updated the prometheus plugin, because RMQ 3.8.1 hasn't got every metric optimization. I will consult my colleague who was responsible for the optimization. As far as I can remember we also did tests disabling all metric and management plugins without any stability improvements.

**advanced.config** 
```
              {vm_memory_high_watermark, 0.7},
              {queue_index_embed_msgs_below, 0},
              {collect_statistics_interval, 60000}]},
```

The example below is showing the CPU load is more or less normal before and during the RAM peak event occured (non-lazy scenario):

![grafik](https://user-images.githubusercontent.com/1308503/107246840-f6694280-6a30-11eb-8850-e8d1523e9518.png)

Using the `export-definition-50k-empty-non-lazy.json` definition the docker container is permanently gathering metrics (total reductions) but isn't under intense CPU pressure. 

**Docker workstation**: 1 node x 6 cores - Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz, 3601 MHz - ~ 30% metric cpu load
**Test environment**: 3 nodes x 6 cores - Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz - ~ 25 % metric cpu load

```
|Home(H)|Network(N)|System(S)|Ets(E)/Mnesia(M)|App(A)|Doc(D)|Plugin(P)recon:proc_count(memory, 18) Interval:5000ms     | 0Days 19:45:54   |
|Erlang/OTP 23 [erts-11.1.7] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1]                                                    |
|System     | Count/Limit           | System Switch             | Status                | Memory Info          | Size                     |
|Proc Count | 101210/1048576        | Version                   | 23.2.3                | Allocted Mem         | 8.8742 GB       | 100.0% |
|Port Count | 12/1048576            | Multi Scheduling          | enabled               | Use Mem              | 1.6899 GB       | 19.04% |
|Atom Count | 47472/5000000         | Logical Processors        | 6                     | Unuse Mem            | 7.1842 GB       | 80.96% |
|Mem Type   | Size                  | Mem Type                  | Size                  | IO/GC                | Interval: 5000ms         |
|Total      | 6.0449 GB    | 100.0% | Binary                    | 17.6693 MB   | 00.29% | IO Output            | 12.8411 MB               |
|Process    | 3.4299 GB    | 56.74% | Code                      | 31.5554 MB   | 00.51% | IO Input             | 3.9958 MB                |
|Atom       | 1.3868 MB    | 00.02% | Reductions                | 72226478              | Gc Count             | 2673                     |
|Ets        | 2.4915 GB    | 41.22% | RunQueue/ErrorLoggerQueue | 2/0                   | Gc Words Reclaimed   | 235049460                |
||1  |||||||||||||||        70.21% |4                         00.38% |7                         00.00% |10                         00.00% |
||2  |||||||||||||          62.05% |5                         00.03% |8  |                      05.60% |11                         00.00% |
||3  ||||||                 31.18% |6                         00.02% |9  ||                     10.96% |12                         00.00% |

```

We thought the metric collection effort is a constant rate related to the queue, binding and message count. 

To limit the amount of variables feel free to disable or optimize metrics collection.

**Reply by motmot80** [reply]
I think we are also having another a reproduction setup using **non-lazy** queues:

**Reproduction steps:**
1. Single Node with 20 GB RAM, Nvme M.2 Storage, 6 Cores (0.7 high watermark)
2. Load the definition `export-definition-50k-empty-non-lazy.json`
3. Use perftest to publish the first 1M messages `perftest --predeclared --exchange <XXXX SEE OFFICIAL TICKET>--routing-key <XXXX-YY SEE OFFICIAL TICKET> -f persistent --consumers 0 --producers 1 --slow-start --rate 1 --time 20 `
4. Wait 2-3 hours till everything is settled (**8 GB RAM used**)
5. Use perftest again: `perftest --predeclared --exchange <XXXX SEE OFFICIAL TICKET> --routing-key <XXXX-YY SEE OFFICIAL TICKET> -f persistent --consumers 0 --producers 1 --slow-start --rate 1 --time 20 `

**Expected:**
Node may be to slow to handle 50k msg/sec but keeps stable.

**Actual:**
A few seconds after the publish finished the node RAM usage is steadily increasing, does not stop at high watermark (14 GB) and crashes at 19 GB RAM.

**Right before crashing (low CPU but high RAM usage):**

```
CONTAINER ID        NAME                              CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
9b21cdfa6852        compose-binding-test_rabbitmq_1   114.57%             18.85GiB / 19.32GiB   97.56%              164MB / 186MB       254MB / 10.7GB      95
```

This also isn't exactly what happened on the test environment, because there were no huge fan out activities, but the result is quite similar to what we've seen looking at the system stats.

**Reply by gerhard** [reply]
Metrics are cheap compared to stats. We made this simple change:

```diff
  rabbitmq:
    additionalConfig: |
      disk_free_limit.relative = 1.0
      vm_memory_high_watermark.relative = 0.7
      log.file.level = debug
+      # management metrics can be disabled altogether
+      management_agent.disable_metrics_collector = true
```

And the difference for 50k queues with no activity is 0.58 vs 0.13 CPUs & 2.2GB vs 4GB RAM:

With stats:

![image](https://user-images.githubusercontent.com/3342/107255839-a12d3100-6a30-11eb-9b90-be247e3dd63a.png)

![image](https://user-images.githubusercontent.com/3342/107256093-f49f7f00-6a30-11eb-9876-41c44cf3bf54.png)

Without stats:

![image](https://user-images.githubusercontent.com/3342/107255866-aab69900-6a30-11eb-8d7e-a7da40af17b1.png)

![image](https://user-images.githubusercontent.com/3342/107255921-b6a25b00-6a30-11eb-80c1-1820b49d9d24.png)

We got side-tracked by the high CPU utilisation after the queues finish importing. Leaving it aside for now and re-focusing on reproducing what you are observing, so that we zone in on the reported issue.

**Reply by motmot80** [reply]
Following your interesting side-track while waiting... 
We are using the classic configuration.  The settings seems to have no impact in my case, but maybe I missconfigured something.

**advanced.config**

```
[
  {rabbitmq_management_agent, [{disable_metrics_collector, true}]}
].
```

`rabbitmqctl environment` looks like this

```
{rabbitmq_management_agent,
     [{rates_mode,basic},
      {sample_retention_policies,
          [{global,[{605,5},{3660,60},{29400,600},{86400,1800}]},
           {basic,[{605,5},{3600,60}]},
           {detailed,[{605,5}]}]}]},

```
The management web ui is working, too.

Any idea what I am doing wrong?

**Reply by gerhard** [reply]
Will pick this up tomorrow - long day today.

@dcorbacho or @michaelklishin may beat me answering your last question, otherwise I'll address first thing tomorrow.

**Reply by gerhard** [reply]
That config looks correct, but you must be defining it in a place that RabbitMQ does not read the config from.

Confirming that it works as expected:

```
cat rabbitmq.config
[
  {rabbitmq_management_agent, [{disable_metrics_collector, true}]},
  {rabbit, [{loopback_users, []}]}
].

docker run -it --name disable_metrics_collector --rm -e RABBITMQ_ADVANCED_CONFIG_FILE=/etc/rabbitmq/rabbitmq.config -v $PWD/rabbitmq.config:/etc/rabbitmq/rabbitmq.config rabbitmq:3.8.11-management

docker exec -it disable_metrics_collector rabbitmqctl environment | grep -A 2 rabbitmq_management_agent
 {rabbitmq_management_agent,
     [{disable_metrics_collector,true},
      {rates_mode,basic},
```

**Reply by gerhard** [reply]
This is what we have deployed currently:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: vesc-1002
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: lazy
  namespace: vesc-1002
spec:
  replicas: 1
  image: rabbitmq:3.8.11-management
  resources:
    requests:
      cpu: 12
      memory: 50Gi
    limits:
      cpu: 12
      memory: 50Gi
  persistence:
    storageClassName: ssd
    storage: 100Gi
  rabbitmq:
    additionalConfig: |
      disk_free_limit.relative = 1.0
      vm_memory_high_watermark.relative = 0.7
      log.file.level = debug
      # This defaults to min-masters when RabbitMQ is deployed via Cluster Operator, which is not optimal in this case.
      # Considering that there is a single Rabbit node, this should be ignored and be fast, but it isn't.
      # Using the RabbitMQ default explicitly addresses the slow queue declarations (30/s @ 15k, 20/s @ 20k, 10/s @ 40k, etc.)
      queue_master_locator = client-local
      # management metrics can be disabled altogether
      management_agent.disable_metrics_collector = true
  tolerations:
  - key: dedicated
    operator: Equal
    value: vesc-1002
    effect: NoSchedule
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            nodeSelector:
              com.rabbitmq: vesc-1002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lazy-perftest
  namespace: vesc-1002
spec:
  replicas: 0
  selector:
    matchLabels:
      app: lazy-perftest
  template:
    metadata:
      labels:
        app: lazy-perftest
    spec:
      tolerations:
      - key: dedicated
        operator: Equal
        value: vesc-1002
        effect: NoSchedule
      nodeSelector:
        com.rabbitmq: vesc-1002
      containers:
      - name: perftest
        image: pivotalrabbitmq/perf-test:dev-2021.02.10
        ports:
        - containerPort: 8080
          name: prometheus
        command:
        - /bin/bash
        - -c
        args:
        - |-
          bin/runjava com.rabbitmq.perf.PerfTest \
            --uri amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_SERVICE} \
            --exchange TestExchange --type topic \
            --queue-pattern 'queue%d' --queue-pattern-from 1 --queue-pattern-to 50000 \
            --queue-args 'x-queue-mode=lazy' \
            --auto-delete false --flag 'persistent' \
            --routing-key 'route5' \
            --producers 1 \
            --variable-rate '1:20' \
            --variable-rate '0:300' \
            --variable-rate '1:20' \
            --variable-rate '0:600' \
            --variable-rate '1:20' \
            --variable-rate '0:1800' \
            --variable-rate '1:20' \
            --variable-rate '0:3600' \
            --variable-rate '1:20' \
            --variable-rate '0:7200' \
            --consumers 0 \
            --metrics-prometheus true
        env:
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: lazy-default-user
              key: username
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: lazy-default-user
              key: password
        - name: RABBITMQ_SERVICE
          value: lazy

```

We don't import definitions from file because https://github.com/rabbitmq/rabbitmq-server/issues/2800#issuecomment-776194822

You will notice that we publish 1 msg/s for 20 seconds, then stop for 5 minutes, publish 1 msg/s for 20 seconds, then stop for 30 minutes etc. (see the lines containing `--variable-rate` for the full cycle).

This is what we are seeing from a memory allocator perspective:

![image](https://user-images.githubusercontent.com/3342/107531326-a31ffd00-6bb4-11eb-97ea-a87148bf7257.png)

Second time messages are published, RSS spikes to 13GB.

30 minutes later, same publishing rates pushes RSS to 24GB.

1 hour later, RSS grows to 33GB.

This is definitely not expected or normal, and all things still point to the Erlang VM not behaving correctly under memory pressure. We have more questions than answers at this point, and this is what we are doing next:

* wait for the next publishing interval and run `rabbitmqctl eval 'recon_alloc:allocators().'` a few times so that we capture the state of the Erlang allocators
* diff this state to the normal state and figure out what doesn't look right
* submit bug report to the Erlang team
* attempt a few short-term fixes - we are deploying a second environment where we can try this, while observing the current one eventually lock up, same as you have reported

I don't expect a quick fix, we are likely to be here for a few more days at least. If we are lucky, we will have an Erlang bug report today. The important thing is that we are still very much digging into this, just that it's hard and slow going, but I am positive that we will get to the bottom of this 😉
