### DISCUSSION TITLE
Providing exported JSON config for RabbitMQ cluster in Kubernetes cluster

### DISCUSSION THREAD

**Discussion by jxsl13** [rabbitmq/rabbitmq-server#2828] [Questions] [answered]
Hey, I'd like to provide some initial policy configuration at startup of a RabbitMQ cluster. What would be the best way to do that?

My current configuration looks like this:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqcluster
spec:
  replicas: 3

  persistence:
    storage: 2Gi
  resources:
      requests:
        cpu: 100m
        memory: 384Mi
      limits:
        cpu: 100m
        memory: 384Mi
  override:
    statefulSet:
        spec:
          template:
            metadata:
              labels:
                cluster: rabbitmqcluster
            spec:
              containers:
                - name: rabbitmq
                  readinessProbe:
                    periodSeconds: 5
                    failureThreshold: 120
              # try not to schedule two pods on the same node
              affinity:
                podAntiAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      # use hostname for anti-affinity
                      topologyKey: kubernetes.io/hostname
                      labelSelector:
                        matchExpressions:
                        - key: cluster
                          operator: In
                          values:
                          - rabbitmqcluster
  rabbitmq:
    additionalConfig: |
      log.console = true
      disk_free_limit.absolute = 50MB
      vm_memory_high_watermark.relative = 0.95
    #advancedConfig: |
```
