### DISCUSSION TITLE
Quorum queues frequent memory issues

### DISCUSSION THREAD

**Discussion by liorhasson** [rabbitmq/rabbitmq-server#3199] [Other] [answered]
Hi,

Summary: 
Rabbitmq 3.8.16, with hundreds of quorum queues (~900).
Cluster of 3 nodes, on k8s, memory limit up to 4G per node.

What goes wrong?

1. The memory is keep on growing in a moderate manner, although the number of queues and connections are stable.
2. Node restarting taking more and more time, at the beginning it took ~2 min, now after 2 weeks, it takes ~10 min.

Attachment of one node memory usage in 14 days time range:
![Screen Shot 2021-07-18 at 15 36 16](https://user-images.githubusercontent.com/492604/126067325-f4994ad9-8848-4c7c-96db-5c3aa67c00de.png)

![Screen Shot 2021-07-18 at 11 55 59](https://user-images.githubusercontent.com/492604/126067391-ae842449-7139-4ece-b310-e8f507cc3381.png)

Regards

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(

**Comment by michaelklishin** [comment]
You haven't provided much evidence that this is indeed quorum queues that are responsible. There are tools that [can produce a breakdown](https://rabbitmq.com/memory-use.html).

The fact that node restart takes longer over time suggests that the on-disk quorum queue (Raft) log is growing and not truncated.
This can be due to the fact that your consumers [**consume but never acknowledge** messages](https://www.rabbitmq.com/quorum-queues.html#repeated-requeues). It can also be due to the fact
Quorum queues keep a certain amount of recent log entries in memory, and [this footprint can be reduced via configuration](https://www.rabbitmq.com/quorum-queues.html#resource-use).

**Comment by michaelklishin** [comment]
While [this Raft library PR](https://github.com/rabbitmq/ra/pull/222) won't help with an ever-growing log that's not truncated because messages are not acknowledged, log recovery will be double digit % more efficient in [RabbitMQ 3.9](https://blog.rabbitmq.com/posts/2021/07/rabbitmq-3.9.0-release-calendar/). [Streams](https://blog.rabbitmq.com/posts/2021/07/rabbitmq-streams-overview/) will be a much better option for large backlogs compared to quorum queues, too.

**Comment by michaelklishin** [comment]
Also, with 900 quorum queues you'd have to significantly limit the number of log entries kept both on disk and in memory. The limits in the doc guide above are **per queue**. The defaults is optimal for 8-12 queues that have to carry peak throughput, not hundreds.

**Comment by kjnilsson** [comment, marked as answer]
As @michaelklishin have said we need a lot more information to tell what is actually going on. It does look like there is a memory growth of _something_ over time. Perhaps it is related to the number of queues you have but without more information we cannot say. A simple experiment, as I suggested to you in the community slack, is to execute `rabbitmqctl force_gc` on a node and see how that affects memory use.

Regarding the node restart slowness it can vary. What would be helpful are full logs at debug that cover the timeframe of the restart. Ideally from _all_ RabbitMQ nodes. What also would be helpful is more details on what kind of disks you use, what throughput they can sustain, disk stats during node recovery and also how many cores your servers have.

**Comment by gerhard** [comment]
Memory-growth is one of my special interest areas, thanks for highlighting this topic @kjnilsson!

Can you share with us @liorhasson the [Erlang-Memory-Allocators](https://grafana.com/grafana/dashboards/11350) dashboard view over the same period? A [public snapshot](https://www.youtube.com/watch?v=L-tYXpirbpA&t=551s) would be ideal, but a screenshot will be better than nothing. [This is a good intro to how I think about the metrics visualised by Erlang-Memory-Allocators](https://youtu.be/NWISW6AwpOE?t=530).

Lastly, we have a number of long-running workloads that we have been running for years against RabbitMQ clusters. If you can capture your workload in a K8s deployment, the one that results in this memory growth, I would be up for setting it up in our 3.8 LRE (Long Running Environment) and observing what happens over a week. Thanks @liorhasson!

**Reply by liorhasson** [reply]
Hello @gerhard,

I'm preparing the Erlang-Memory snapshot.

Regarding the cluster workload, How can I capture the k8s workload? can you elaborate

Thanks for the help

**Reply by gerhard** [reply]
https://github.com/rabbitmq/cluster-operator/blob/main/docs/examples/production-ready/rabbitmq.yaml combined with the following are a good starting point:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perf-test
  namespace: discuss-3199
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perf-test
  template:
    metadata:
      labels:
        app: perf-test
    spec:
      containers:
        - name: perf-test
          image: pivotalrabbitmq/perf-test
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
          command:
            - /bin/bash
            - -c
          args:
          - |-
            bin/runjava com.rabbitmq.perf.PerfTest \
              --uri amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_SERVICE}:${RABBITMQ_SERVICE_PORT_AMQP} \
              --flag persistent \
              --auto-delete false \
              --queue-args x-queue-mode=lazy \
              --variable-size 10000:60 --variable-size 12000:60 \
              --queue-pattern 'perf-test-%d' --queue-pattern-from 1 --queue-pattern-to 10 \
              --exchange perf-test --type topic \
              --producers 100 --confirm 5 \
              --consumers 150 --qos 10
          env:
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-default-user
                key: username
          - name: RABBITMQ_PASS
            valueFrom:
              secretKeyRef:
                name: rabbitmq-default-user
                key: password
          - name: RABBITMQ_SERVICE
            value: rabbitmq

```

Add multiple PerfTest deployments if needed. This will help figuring out what PerfTest options there are so that you can simulate your workload more accurately: https://rabbitmq.github.io/rabbitmq-perf-test/stable/htmlsingle/

You can also reference container images for your own app if they are publicly available.
