### DISCUSSION TITLE
The .erlang.cookie file content does not have the expected initial value.

### DISCUSSION THREAD

**Discussion by myesn** [rabbitmq/rabbitmq-server#3353] [Other] [answered]
The cookie file content does not have the expected initial value.

docker-compose.yml

```yml
version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9.5-management
    hostname: rabbit01
    container_name: rabbitmq
    restart: always
    environment: 
      - RABBITMQ_ERLANG_COOKIE=GBMQWMMYXWMEBYDDHYVQ
    volumes:
      - ./dockerfiles/rabbitmq/data:/var/lib/rabbitmq3
      - ./dockerfiles/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf      
```

After starting the service, I go inside the container through `exec`, and then view `/root/.erlang.cookie`  and `/var/lib/rabbitmq/.erlang.cookie`, The contents of a cookie file is `TVCCUOTBYAGPINTFQKXX`. 

![image](https://user-images.githubusercontent.com/18598579/131461604-d662a10e-f6f9-4eaf-a3f8-2aaea67b9d5d.png)

Could you tell me what I did wrong?
