### DISCUSSION TITLE
Messaging Topology Operator & Users: no matches for kind 'User'

### DISCUSSION THREAD

**Discussion by irperez** [rabbitmq/rabbitmq-server#3427] [Questions]
In regards to the RabbitMQ Cluster Operator and the Messaging Topology Operator.  I'm looking to create a user.

I'm trying to follow this article: https://www.rabbitmq.com/kubernetes/operator/using-topology-operator.html

In particular I'm trying to create the following object in my cluster.

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: import-user
spec:
  rabbitmqClusterReference:
    name: rabbitmq-rgodfrey
  importCredentialsSecret:
    name: rabbit-credentials-secret
```

I get the following error from my cluster.

```
no matches for kind "User" in version "rabbitmq.com/v1beta1"
```

I'm following the documentation.  It seems that the Messaging Topology Operator and its objects are installed as part of the RabbitMQ Cluster Operator.  If not, the documentation does not say where the Messaging Topology Operator gets installed from.  Any guidance would be great, thanks!
