### DISCUSSION TITLE
Can't add a new trace

### DISCUSSION THREAD

**Discussion by ysjjovo** [rabbitmq/rabbitmq-server#3857] [Other]
Steps to reproduce.
Setup rabbitmq cluster with tracing plugin enabled.
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: def
  namespace: default
spec:
  image: rabbitmq:3.9.11
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 500m
      memory: 500Mi
  persistence:
    storageClassName: hostpath
    storage: 1Gi
  service:
    type: NodePort
  rabbitmq:
    additionalPlugins:
      - rabbitmq_tracing
```
Then going to management UI,admin tab,tracing menu,input name 'df',last click 'Add trace' button',here is the prompt error messages.
```
Node 'rabbit@def-server-0.def-nodes.default' could not be contacted: {badrpc,
...
```
But trace log successfully generated in the target file.
```
 kubectl exec def-server-0 -- cat /var/tmp/rabbitmq-tracing/gf.log

Defaulted container "rabbitmq" out of: rabbitmq, setup-container (init)

================================================================================
2021-12-06 8:56:38:529: Message published

Node:         rabbit@def-server-0.def-nodes.default
Connection:   192.168.65.3:48300 -> 10.1.0.100:5672
Virtual host: /
User:         default_user_EtvssC4bIGU7rznNoCy
Channel:      1
Exchange:     logs_topic
Routing keys: [<<"-test.run">>]
Routed queues: []
Properties:   [{<<"content_type">>,longstr,<<"text/plain">>}]
Payload:
^TestSend$
...
```
Aditional environment info
```
➜  rabbitmq cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
➜  rabbitmq kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
