### DISCUSSION TITLE
rabbitmq management login failed

### DISCUSSION THREAD

**Discussion by seqwait** [rabbitmq/rabbitmq-server#4319] [Other]
I used  docker secrets as below, but it's doesn't work,  used /run/secrets/rabbit_password text password cannot login web
but if I update DEFAULT_PASS_FILE to DEFAULT_PASS: XXXX it works well, I don't know what happened?

compose
```
version: '3.7'
services:
  rabbit:
    image: rabbitmq-prod:3.9.13-management
    environment:
      DEFAULT_USER: admin
      DEFAULT_PASS_FILE: /run/secrets/rabbit_password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      overall_test:
        aliases:
          - box.rabbit.io
    secrets:
      - rabbit_password
    deploy:
      placement:
        constraints:
          - "node.labels.box.rabbit == yes"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: "4g"
          cpus: "2"

secrets:
  rabbit_password:
    file: rabbit_password.txt

networks:
  overall_test:
    driver: overlay
    name: overall_test
    attachable: true
```
