### DISCUSSION TITLE
RabbitMQ Cluster created via RabbitMQ Operator and Istio integration

### DISCUSSION THREAD

**Discussion by lordigon** [rabbitmq/rabbitmq-server#5226] [Questions]
Hi everyone,
I created a RabbitMQ cluster using RabbitMQ Operator with this yaml file 

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: test-rabbit
spec:
  replicas: 1
  rabbitmq:
    additionalConfig: |
      log.console.level = info
      default_user= guest
      default_pass = guest
      default_user_tags.administrator = true
    additionalPlugins:
      - rabbitmq_mqtt
      - rabbitmq_jms_topic_exchange
      - rabbitmq_web_mqtt
  service:
    type: ClusterIP
```

 I tried to add Istio and configure it but looking at the result via Kiali console some protocol seems not supported automatically.
 
![Kali-Istio-problem](https://user-images.githubusercontent.com/4588165/178943930-22c33fac-6ed5-4e57-8c43-ffc6ebf5bd20.png)

I'm not an istio expert but reading its documentation Istio automatically manage TCP port using appProtocol property
This is the list of TCP ports used by the RabbitMQ Cluster with appProtocol values

```
 ports:
  - appProtocol: amqp
    name: amqp
    nodePort: 32204
    port: 5672
    protocol: TCP
    targetPort: 5672
  - appProtocol: http
    name: management
    nodePort: 30513
    port: 15672
    protocol: TCP
    targetPort: 15672
  - appProtocol: mqtt
    name: mqtt
    nodePort: 31327
    port: 1883
    protocol: TCP
    targetPort: 1883
```

so amqp within appProtocol filed is not recognised as valid Istio supported protocol.
Looking at [Istio documentation](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/) supported protocol values inside appProtocol field are:

http, http2, https, tcp, pls, grpc, grpc-web, mongo, mysql, redis.

Is that a bug or something is missing me?

Best regards,
Flavio

**Comment by lukebakken** [comment]
Based on the documentation you should use `tcp`, **NOT** `amqp`

**Reply by lordigon** [reply]
The problem is RabbitMQ services statefulsets and other resources with their properties (like appProtocol) are created and managed by the operator so they are not under my control...as far as I know.

**Comment by Gsantomaggio** [comment]
>so amqp within appProtocol filed is not recognised as valid Istio supported protocol.

What you see it is just a warning and not an actual problem:
When you enable mTLS:
```yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
```

The Pods are in mTLS, you can test it with `openssl s_client -connect <<RABBITMQ-SERVICE>>:5672` for ex:
```
openssl s_client -connect rabbitmq-prod:5672 
Can't use SSL_get_servername
depth=1 O = cluster.local
verify error:num=19:self signed certificate in certificate chain
verify return:1
depth=1 O = cluster.local
verify return:1
depth=0
verify return:1
140629418255680:error:1409445C:SSL routines:ssl3_read_bytes:tlsv13 alert certificate required:../ssl/record/rec_layer_s3.c:1543:SSL alert number 116
CONNECTED(00000003)
---
Certificate chain
 0 s:
   i:O = cluster.local
 1 s:O = cluster.local
   i:O = cluster.local
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDTjCCAjagAwIBAgIRAMG+5j/JZ8s+3b+XDQ7YFkwwDQYJKoZIhvcNAQELBQAw
GDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDAeFw0yMjA3MTQyMjQ3NTJaFw0yMjA3
MTUyMjQ5NTJaMAAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCv52Iy
qlMP3I0kKjjX35bbv4tRZZjo0rBEMFMDvPBDd4w0/6LNxHhmpAz06OU+YTvCjZm
..........
```

you can easily test what happens if you disable the mTLS :
```
openssl s_client -connect rabbitmq-prod:5672
CONNECTED(00000003)
140619414811968:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 283 bytes
```

As you can see, the pod is not in TLS anymore. 

Same for the Management UI:
```
 curl -kv  https://rabbitmq-prod:5672
*   Trying 10.116.20.119:5672...
* TCP_NODELAY set
* Connected to rabbitmq-prod (10.116.20.119) port 5672 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
istio-proxy@rabbitmq-prod-server-0:/$ curl -kv  https://rabbitmq-prod:5672
*   Trying 10.116.20.119:5672...
* TCP_NODELAY set
* Connected to rabbitmq-prod (10.116.20.119) port 5672 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: [NONE]
*  start date: Jul 15 17:57:22 2022 GMT
*  expire date: Jul 16 17:59:22 2022 GMT
*  issuer: O=cluster.local
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* OpenSSL SSL_write: Broken pipe, errno 32
* Failed sending HTTP2 data
```

**Comment by bkoncz** [comment]
@lordigon Did you ever manage to solve this?

**Reply by kxiong0** [reply]
In case anyone is still looking, you can overwrite the appPortocols similar to how the [additional ports example](https://github.com/rabbitmq/cluster-operator/blob/main/docs/examples/additionalPorts/rabbitmq.yaml) creates new ports. 
Something like this worked for me:
```
spec:
  replicas: 3
  override:
    service:
      spec:
        ports:
          - name: prometheus
            protocol: TCP
            port: 15692
            targetPort: 15692
            appProtocol: tcp
```
