### DISCUSSION TITLE
enable metrics_collector

### DISCUSSION THREAD

**Discussion by yanqin001** [rabbitmq/rabbitmq-server#6697] [Questions]
On the management UI web, if click the "Channels" button, it will show "Stats in management UI are disabled on this node“
![image](https://user-images.githubusercontent.com/69463077/208425247-ed04b783-9a98-47ea-9756-720be958172a.png)

i add "management_agent.disable_metrics_collector = false" config in the rabbitmq yaml like this
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: kb-rabbitmq
  namespace: kb
spec:
  replicas: 3
  resources:
    requests:
      cpu: 2
      memory: 5Gi
    limits:
      cpu: 2
      memory: 5Gi
  rabbitmq:
    additionalConfig: |
      default_user=admin
      default_pass=9zPd2h8A
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
      management_agent.disable_metrics_collector = false
  persistence:
    storageClassName: longhorn
    storage: "100Gi"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - kb-rabbitmq
        topologyKey: kubernetes.io/hostname
```
but the config dose not work, how the channels info can be seen from the webpage.

**Comment by mkuratczyk** [comment]
There is no mention of the image in your definition. What image are you using?

**Reply by yanqin001** [reply]
operator image is rabbitmqoperator/cluster-operator:2.0.0
rabbitmq image is rabbitmq:3.9.26

**Comment by qibint** [comment]
@mkuratczyk Having the same issue with enabling the metrics collector through this additionalConfig.
image: rabbitmq:3.11.10
rabbitmqoperator/cluster-operator:2.1.0
Can you help? Thanks

**Reply by qibint** [reply]
There is a separate config file named management_agent.disable_metrics_collector.conf under rabbitmq config.d folder where I think we should set it up. Currently, it's been configured in 90-userDefinedConfiguration.conf through cluster-operator additionalConfig option.

**Reply by mkuratczyk** [reply]
You can just use `rabbitmq:3.11.11-management` image and you'll have it enabled. If that's not what you want, please provide commands I can run to see the problem.

**Reply by qibint** [reply]
Hey @mkuratczyk.
We're using RabbitMQ Cluster Kubernetes Operator and create the rabbitmq instances from it following - https://www.rabbitmq.com/kubernetes/operator/using-operator.html#advanced-config. I will definitely need the flexibility to turn on/off this metric through this configuration file.

**Reply by mkuratczyk** [reply]
Please provide your YAML.

PS No need to mention me in every post. :)

**Reply by qibint** [reply]
Thank you for looking into this.
The config is simple:

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: amqp-workers
spec:
  image: rabbitmq:3.11.10
  service:
    type: ClusterIP
  replicas: 3
  persistence:
    storage: 20Gi
    storageClassName: gp2
  rabbitmq:
    additionalConfig: |
      # https://www.rabbitmq.com/configure.html
      # management metrics can be disabled altogether
      management_agent.disable_metrics_collector = false
```
