### DISCUSSION TITLE
Rabbitmq stream coordinator fails to start after the restore of PVC snapshot backup using Kasten k10

### DISCUSSION THREAD

**Discussion by andreapulvirenti** [rabbitmq/rabbitmq-server#8060] [Other]
### Describe the bug

We need to backup the snapshot of the volumes for rabbitmq streams with all its messages. in order to recover it.
Rabbitmq it's deployed in a AKS cluster through the bitnami chart (version 11.13.0)  in High Availabilty mode with 3 nodes (PodAntiaffnityPreset: Hard). 
Kasten is deployed with version 1.0.31 
[https://docs.kasten.io/latest/install/azure/azure.html](url)

Accordingly with documentation of rabbitmq:

[https://www.rabbitmq.com/backup.html](url)

 that I quotes: 

> **To back up messages on a node it must be first stopped.**
> 
> In the case of a cluster with [replicated queues](https://www.rabbitmq.com/quorum-queues.html), it is highly recommended to stop the entire cluster over a period of time to take a backup. If instead one node is topped at a time, queues may accumulate duplicates, exactly like when you back up a single running node.
> 
> If the majority of cluster nodes is stopped rapidly quorum queues may lose their availability, and as a result miss a small percentage of recent publishes to them.

we made a custom blueprint with pre-backup hook and post-backup hook like this: 

```yaml 
apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: volume-snapshot-blueprint
  namespace: kasten-io
actions:
  backupPrehook:
    kind: StatefulSet
    phases:
      - args:
          command:
            - /bin/sh
            - '-c'
            - |
              rabbitmqctl stop_app
          container: rabbitmq
          namespace: namespace1
          pod: rabbitmq-0
        func: KubeExec
        name: rabbitfreeze
  backupPosthook:
    kind: StatefulSet
    phases:
      - args:
          command:
            - /bin/sh
            - '-c'
            - |
              rabbitmqctl start_app
          container: rabbitmq
          namespace: namespace1
          pod: rabbitmq-0
        func: KubeExec
        name: rabbitunfreeze
```

what we are trying to achive is that the rabbitmq application stay up and running during the backup of the PersistentVolume so as you can see we stopped the node 0 of the statefulset and restart it after backup. We backup and restore JUST the node 0 of the rabbitmq application.
That's seems to work.

![image](https://user-images.githubusercontent.com/14847376/235104224-39229640-0bd4-4757-b07b-e6cf16a1a335.png)

![image](https://user-images.githubusercontent.com/14847376/235099405-ecb2cc56-c551-4600-a242-bb4f16018dec.png)

we expecting that restoring of node 0  would mirror all the stream queue in the other nodes.
the restore of kasten is completed successfully but the stream queues restored are all in down state
as you can see here: 
![image](https://user-images.githubusercontent.com/14847376/235100410-d5d59fd8-c23e-41d7-81b2-632d0124ba4e.png)

even if we try to create a new stream rabbitmq freeze for some seconds and after few seconds this error is prompt: 
![image](https://user-images.githubusercontent.com/14847376/235102048-ab508334-0f29-488b-922f-f930996f6cff.png)
 
logs says:
```
rabbitmq
2023-04-28 09:02:56.774251+00:00 [error] <0.13551.20>
rabbitmq
2023-04-28 09:02:57.407828+00:00 [warning] <0.32479.22> Coordinator timeout on server 'rabbit@rabbitmq-0.rabbitmq-headless.tp-oiadp-bus.svc.cluster.local' when processing command new_stream
rabbitmq
2023-04-28 09:02:57.426632+00:00 [warning] <0.32479.22> Declare queue error: Cannot declare a queue 'queue 'test-test' in vhost '/'' on node 'rabbit@rabbitmq-0.rabbitmq-headless.tp-oiadp-bus.svc.cluster.local': {error,coordinator_unavailable}
```

I would really appreciate to have your support, any idea would be useful.
Let me know if you need some details. 
Thank you all

### Reproduction steps

1. Install rabbitmq bitnami chart with 3 replicas on the cluster ( version: 11.13.0 )
2. Install kasten k10 on the cluster  with the blueprint CRD mentioned above (version: 1.5.0)
3. Access on rabbitmq UI application and create some stream queue
4. publish random messages on queues created before
5. Access on kasten k10 application
6. Create a policy in kasten to backup the snapshot of volume data-rabbitmq-0 
7. Specify in the kasten policy the prehook and posthook declared in the "volume-snapshot-blueprint" blueprint
![image](https://user-images.githubusercontent.com/14847376/235116344-d6ac2bf0-9cd0-4ffc-a038-57e73f70b18d.png)
![image](https://user-images.githubusercontent.com/14847376/235116674-6932e53b-7065-43d1-be3d-202563442b4a.png)
8. Run the policy and run it to create the backup 
9. Reinstall rabbitmq application just to simulate a disaster and delete all the stream queues
10. Find your application in kasten and restore with the backup created before
11. Access on the rabbitmq application and you can see the streams are not running
...

### Expected behavior

Stream queue should be up and running after the restore of the volume

### Additional context

Kubernetes cluster
