### DISCUSSION TITLE
Cluster with all Quorum Queues performance limits

### DISCUSSION THREAD

**Discussion by pecigonzalo** [rabbitmq/rabbitmq-server#8113] [Questions]
Hi! We are running a cluster with around 50 Queues and PerfTest to test the limits of a given cluster setup and try to understand the metrics that will indicate our cluster does not have more capacity.

So far, we have been unable to find clear metrics of the cluster reaching its limit aside from the side-effect of the latency on the PerfTest metrics.

Setup:
- Deployment Method: Kuberentes Operator
- NodeGroup
  - Storage with GP3, 1000 IOPS, 125MB
  - Type: `c5.4xlarge`

Cluster config:
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: cluster-a
  namespace: rabbitmq
spec:
  replicas: 3
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 12
      memory: 16Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_federation
      - rabbitmq_federation_management
    additionalConfig: |
      management.path_prefix = /rabbitmq-cluster-a
      log.console = true
      log.console.level = info
      log.console.formatter.json.field_map = verbosity:v time msg domain file line pid level:-
      log.console.formatter.json.verbosity_map = debug:7 info:6 notice:5 warning:4 error:3 critical:2 alert:1 emergency:0
      log.console.formatter.time_format = epoch_usecs
      cluster_partition_handling = pause_minority
      collect_statistics_interval = 10000
    # Disable RABBITMQ_LOGS=- which is set in
    # https://github.com/docker-library/rabbitmq/blob/ece63d4534cc44abd6b1ec35bbd9aa0d21e87e1d/3.9/ubuntu/Dockerfile#L211
    # Otherwise, this environment variable will override all log configurations in additionalConfig.
    envConfig: |
      RABBITMQ_LOGS=""
  persistence:
    storageClassName: ebs-sc
    storage: "50Gi"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - cluster-a
          topologyKey: kubernetes.io/hostname
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            topologySpreadConstraints:
              - maxSkew: 1
                topologyKey: "topology.kubernetes.io/zone"
                whenUnsatisfiable: DoNotSchedule
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: cluster-a
```

- We put no limits to avoid any CPU throttling potential problems that were present in K8s (We tried with limits as well)

PerfTest Config
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: perftest
  namespace: default
spec:
  serviceName: perftest
  podManagementPolicy: "Parallel"
  replicas: 0
  selector:
    matchLabels:
      app: perftest
  template:
    metadata:
      labels:
        app: perftest
    spec:
      containers:
        - name: perftest
          image: pivotalrabbitmq/perf-test
          env:
            - name: QUEUE_PATTERN
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: QUEUE_COUNT
              value: "1"
          args:
            - --metrics-prometheus
            - --uri
            - "amqp://perf:perf@cluster-a.rabbitmq.svc.cluster.local"
            - -f
            - persistent
            - -ad
            - "false"
            - -qq
            - -mpr
            - --queue-pattern
            - "$(QUEUE_PATTERN)-%d"
            - --queue-pattern-from
            - "1"
            - --queue-pattern-to
            - "$(QUEUE_COUNT)"
            - --producer-random-start-delay
            - "60"
            - --producers
            - "1"
            - --confirm
            - "100"
            - --confirm-timeout
            - "5"
            - --consumers
            - "2"
            - --qos
            - "100"
            - --multi-ack-every
            - "10"
            - -s
            - "1000"
            - --rate
            - "1000"
            - --use-millis
          ports:
            - name: metrics
              containerPort: 8080
```

- Queues are replicated across 3 brokers (leader + 2 replicas)
- We use a statefulset so we can scale load by scaling the replica count
- We target 1Mb/s per pod via 1Kb messages at 1000 rate (similar to the benchmarks in the RMQ blog)
- We use confirms at 10% according to benchmarks in the RMQ blog
- We use mult-ack at 10% according to benchmarks in the RMQ blog

With this setup we can reach around 30/40K msg/s, but even with more PerfTest pods we cant seem to get more performance and our PerfTest metrics start to go through the roof.

We tried:
- Increasing IOPS/MB of the storage layer (despite no signs of this being the limit)
  - We saw some Raft commit latency, but the disk seem to have spare performance
- Differing tuning parameters
  - sysctl network
  - quorum_commands_soft_limit
  - Disable Nagle's Algorithm ("nodelay")
- Tuning the producers/consumers (least preferred option as it requires deep involvement on each service)

Any help would be appreciated. 

A bit of context: We are essentially trying to run RMQ as a platform for our teams but we have so far found no way of knowing when the cluster is reaching its limits and struggling quite a bit to guarantee or tune performance in this multi-tenancy scenario. eg. A client pushed fat messages, or a client shoves a lot of data (100k/s) suddenly to the cluster, etc. So we are exploring multi-cluster and other options, but at its core we are struggling with having good observability into our cluster, each time we had to analyze bad/good performance we had to dive into how each consumer/producer is using the cluster (is it using confirms, acks, etc).
