### ISSUE TITLE
docker latest is giving startup permission issues on certain machines (ubuntu 20.04 + docker 25.0.3)

### ISSUE THREAD

**Issue by pkfl** [rabbitmq/rabbitmq-server#10604]
### Describe the bug

On some machines, when I start the docker compose up with the following compose.yml file, at startup I get an access error. The same exact compose file works on other OS/docker combinations without any issues. Even with the same docker version and the same OS - I have two machines - one gives the error, and one does not. 

[mq.log](https://github.com/rabbitmq/rabbitmq-server/files/14390157/mq.log)

```
---
x-common: &common
  logging:
    driver: local
  network_mode: host
  restart: unless-stopped

services:
  rabbitmq:
    <<: *common
    # image: "rabbitmq:3-management"
    image: "rabbitmq:latest"
    container_name: rabbitmq
    healthcheck:
      interval: 5s
      start_period: 60s
      test: rabbitmq-diagnostics -q ping
```

### Reproduction steps

1. On an ubuntu 20.04LTS box with docker version 25.0.3 (Docker Compose version v2.24.5)
2. Write the above compose.yml file
3. docker compose up # and then look at the docker logs for the container after 2-3 minutes
On some machines, you will get the error - on other you will not. I am hoping someone here can figure out what the issue is.
...

### Expected behavior

On all machines, we expect that the access error is not there.
