### ISSUE TITLE
oauth2 backend regression from 3.13.0.rc2 to 3.13.0

### ISSUE THREAD

**Issue by lazedo** [rabbitmq/rabbitmq-server#10695]
### Describe the bug

oauth2 backend not working as expected

### Reproduction steps

1. create oauth2 deployments on Kubernetes
```
- dex as oauth2 provider
- oauth2-proxy for {oauth_initiated_logon_type, idp_initiated} 
```
3. create cluster with oauth2 setup using operator
```yaml
spec:
  delayStartSeconds: 30
  image: rabbitmq:3.13.0-rc.2-management-alpine
  override: {}
  persistence:
    storage: 10Gi
  rabbitmq:
    additionalConfig: |
      cluster_name = west
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000

      prometheus.return_per_object_metrics = true

      log.console = true
      log.console.level = info
      auth_backends.1 = internal
      auth_backends.2 = rabbit_auth_backend_oauth2

      # local-cert
      auth_oauth2.https.peer_verification = verify_none
    additionalPlugins:
      - rabbitmq_top
      - rabbitmq_federation
      - rabbitmq_federation_management
      - rabbitmq_consistent_hash_exchange
      - rabbitmq_auth_backend_oauth2
      - rabbitmq_prometheus
    advancedConfig: |
      [
          {rabbitmq_auth_backend_oauth2,
           [{scope_prefix, <<>>}
           ,{verify_aud, false}
           ,{extra_scopes_source, <<"groups">>}
           ,{preferred_username_claims, [<<"email">>, <<"username">>, <<"user_name">>, <<"sub">>]}
           ,{key_config, 
            [{peer_verification, verify_none}
            ,{jwks_url, "https://dex.your.fqdn/keys"}
            ]
            }
           ,{scope_aliases, #{<<"myawesomeorg:admins">> => [<<"tag:administrator">>, <<"configure:*/*/*">>, <<"write:*/*/*">>, <<"read:*/*/*">>]}}
           ]
          }
         ,{rabbitmq_management,
           [{oauth_enabled, true}
           ,{oauth_initiated_logon_type, idp_initiated}
           ,{oauth_provider_url, "https://dex.your.fqdn"}
           ]
          }
      ].
  replicas: 3
```
4. create ingress to management-ui with oauth2-proxy
```yaml
  annotations:
    cert-manager.io/cluster-issuer: your-cert-issuer
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-signin: >-
      https://auth.your.fqdn/oauth2/start?rd=https://$host$request_uri$is_args$args
    nginx.ingress.kubernetes.io/auth-url: https://auth.your.fqdn/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $token $upstream_http_authorization;
      # proxy_set_header Authorization $token;
      auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;

      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
           ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
```
5.  browse to management-ui and verify user is logged in
6.  change image from rabbitmq:3.13.0-rc.2-management-alpine to rabbitmq:3.13.0-management-alpine
7.  browse to management-ui and verify user is `not` logged in

### Expected behavior

user is logged in.

### Additional context

logs seem to indicate that `resource_server_id` is required even when validate_aud is false.
setting a `resource_server_id` doesn't help
certificate on provider url is selfsigned and auth_oauth2.https.peer_verification is set to verify_none
