### ISSUE TITLE
Rabbitmq inter node tls did not work

### ISSUE THREAD

**Issue by bsiara** [rabbitmq/rabbitmq-server#10821]
### Describe the bug

I'm trying to configure inter node tls on 3 nodes cluster and still can not achive working that. Tryed rabbitmq docker image: rabbitmq:3.12.13-management-alpine
with docker-compose.yml:
```
version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.12.13-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      TZ: Europe/Warsaw
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpass
      #RABBITMQ_NODENAME: rabbit@rabbitmq1
      RABBITMQ_ERLANG_COOKIE: Cookie
    volumes:
      - /opt/rmq/local/config:/etc/rabbitmq
      - /opt/rmq/local/data:/var/lib/rabbitmq
      - /opt/rmq/local/log:/var/log/rabbitmq
    network_mode: "host"
    extra_hosts:
      - "rabbitmq1:192.168.125.133"
      - "rabbitmq2:192.168.125.55"
      - "rabbitmq3:192.168.125.246"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    ulimits:
      nproc: 65535
      nofile:
        soft: 100000
        hard: 200000
```

Configuration and log you can find in attachment

Certificates was generated using tls-gen/basic
When I try to conect using openssl all works well:
```
openssl s_client -connect 192.168.125.133:25672   -cert config/certs/client.crt -key config/certs/client.key -CAfile config/certs/ca.crt   -verify 8 -verify_ip 192.168.125.133
verify depth is 8
CONNECTED(00000003)
40E707B7887F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:../ssl/record/rec_layer_s3.c:308:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 300 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```
rabbitmq-diagnosting can not connect to node:
```
rabbitmq-diagnostics cluster_status
Error: unable to perform an operation on node 'rabbit@rabbitmq2'. Please see diagnostics information and suggestions below.

Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more
 * Consult server logs on node rabbit@rabbitmq2
 * If target node is configured to use long node names, don't forget to use --longnames with CLI tools

DIAGNOSTICS
===========

attempted to contact: [rabbit@rabbitmq2]

rabbit@rabbitmq2:
  * connected to epmd (port 4369) on rabbitmq2
  * epmd reports node 'rabbit' uses port 25672 for inter-node and CLI tool traffic 
  * TCP connection succeeded but Erlang distribution failed 
  * suggestion: check if the Erlang cookie is identical for all server nodes and CLI tools
  * suggestion: check if all server nodes and CLI tools use consistent hostnames when addressing each other
  * suggestion: check if inter-node connections may be configured to use TLS. If so, all nodes and CLI tools must do that
   * suggestion: see the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more


Current node details:
 * node name: 'rabbitmqcli-692-rabbit@rabbitmq2'
 * effective user's home directory: /var/lib/rabbitmq
 * Erlang cookie hash: Cookie
```
When I run the cluster nodes they did not see each other.
[advanced.config.txt](https://github.com/rabbitmq/rabbitmq-server/files/14695233/advanced.config.txt)
[enabled_pluginx.txt](https://github.com/rabbitmq/rabbitmq-server/files/14695234/enabled_pluginx.txt)
[inter_node_tls.config.txt](https://github.com/rabbitmq/rabbitmq-server/files/14695235/inter_node_tls.config.txt)
[rabbitmq.conf.txt](https://github.com/rabbitmq/rabbitmq-server/files/14695236/rabbitmq.conf.txt)
[rabbitmq.log.txt](https://github.com/rabbitmq/rabbitmq-server/files/14695237/rabbitmq.log.txt)
[rabbitmq-env.conf.txt](https://github.com/rabbitmq/rabbitmq-server/files/14695238/rabbitmq-env.conf.txt)

### Reproduction steps

Run 3 nodes cluster with attached configuration

### Expected behavior

Nodes join to cluster
