### ISSUE TITLE
pause_minority does not work

### ISSUE THREAD

**Issue by CrazyMushu** [rabbitmq/rabbitmq-server#12160]
I encountered a similar problem. The `cluster_partition_handling = pause_minority` setting is enabled, but after disconnecting one of the 3 nodes, it remains reachable, and applications can still connect to it.

```
rabbitmq.conf: |
      cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
      cluster_formation.k8s.address_type = hostname
      cluster_formation.k8s.host = kubernetes.default
      cluster_formation.node_cleanup.interval = 10
      cluster_formation.node_cleanup.only_log_warning = true
      cluster_partition_handling = pause_minority
      queue_master_locator=min-masters
      disk_free_limit.absolute = 512MB
      vm_memory_high_watermark.absolute = 1GB
      cluster_name = atrabbit.cag.wargaming.net
      prometheus.return_per_object_metrics = true
```
```

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
  namespace: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      volumes:
        - name: config
          configMap:
            name: rabbitmq-config
            items:
            - key: rabbitmq.conf
              path: rabbitmq.conf
            - key: enabled_plugins
              path: enabled_plugins
        - name: rabbitmq-erlang-cookie
          emptyDir: {}
        - name: erlang-cookie-secret
          secret:
            secretName: rabbitmq-erlang-cookie
            defaultMode: 420
      initContainers:
      - name: erlang-cookie-hack
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "cp /tmp/erlang-cookie-secret/.erlang.cookie /var/lib/rabbitmq/.erlang.cookie && chmod 600 /var/lib/rabbitmq/.erlang.cookie"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: rabbitmq-erlang-cookie
          mountPath: /var/lib/rabbitmq/
        - name: erlang-cookie-secret
          mountPath: /tmp/erlang-cookie-secret/
      containers:
      - name: rabbitmq
        image: rabbitmq:management-alpine
        imagePullPolicy: Always
        volumeMounts:
          - name: config
            mountPath: /etc/rabbitmq
            readOnly: true
          - name: rabbitmq-data
            mountPath: /var/lib/rabbitmq/mnesia
          - name: rabbitmq-erlang-cookie
            mountPath: /var/lib/rabbitmq/
        ports:
          - name: http
            protocol: TCP
            containerPort: 15672
          - name: amqp
            protocol: TCP
            containerPort: 5672
          - name: prometheus
            protocol: TCP
            containerPort: 15692
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: RABBITMQ_USE_LONGNAME
            value: "true"
          - name: K8S_SERVICE_NAME
            value: rabbitmq
          - name: RABBITMQ_NODENAME
            value: rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE)
          - name: K8S_HOSTNAME_SUFFIX
            value: .$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE)
          - name: RABBITMQ_DEFAULT_USER
            value: admin
          - name: RABBITMQ_DEFAULT_PASS
            value: admin
        resources:
          limits:
            memory: 1.5Gi
          requests:
            memory: 64Mi
            cpu: 0.2
        livenessProbe:
          exec:
            command:
              - sh
              - -ec
              - rabbitmq-diagnostics -q status
        ## Configure RabbitMQ containers' extra options for liveness probe st.2
        ## ref: https://www.rabbitmq.com/monitoring.html#health-checks
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 20
          failureThreshold: 6
          successThreshold: 1
        readinessProbe:
          exec:
            command:
              - sh
              - -ec
              - rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
        ## Configure RabbitMQ containers' extra options for readiness probe st.3
        ## ref: https://www.rabbitmq.com/monitoring.html#health-checks
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 20
          failureThreshold: 3
          successThreshold: 1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rabbitmq
              topologyKey: kubernetes.io/hostname
```

Reproduction steps: Pause any of the virtual hosts in VMware vSphere, wait for 30 seconds to 1 minute until the Kubernetes cluster reports that the node is unavailable, and then resume the host from the pause. As a result, the RabbitMQ cluster will split, with the cluster divided into two parts – 2 nodes and 1 node will operate in parallel.

<html><body>
<p>
  The nature of the partition is as follows:
</p>
  
Node | Was partitioned from
-- | --
rabbit@rabbitmq-2.rabbitmq.rabbitmq | rabbit@rabbitmq-0.rabbitmq.rabbitmq            rabbit@rabbitmq-1.rabbitmq.rabbitmq

</body>
</html>

At the same time, none of the cluster state check commands will indicate that the 2-node group is in the minority. Examples:

```
/ $ rabbitmq-diagnostics -q alarms
Node rabbit@rabbitmq-2.rabbitmq.rabbitmq reported no alarms, local or clusterwide
```
```
/ $ rabbitmq-diagnostics check_running
Checking if RabbitMQ is running on node rabbit@rabbitmq-2.rabbitmq.rabbitmq ...
RabbitMQ on node rabbit@rabbitmq-2.rabbitmq.rabbitmq is fully booted and running
```

I would expect that in such a scenario, the cluster node that is in the minority would at least shut down its port so that applications can't connect to it, but that's not the case.

Example of checking port availability from inside the container:
```
/ $ rabbitmq-diagnostics check_port_listener 5672
Asking node rabbit@rabbitmq-2.rabbitmq.rabbitmq if there's an active listener on port 5672 ...
A listener for port 5672 is running on node rabbit@rabbitmq-2.rabbitmq.rabbitmq.
```

Example of checking port availability from another Kubernetes namespace:

```
/app # telnet rabbitmq-2.rabbitmq.rabbitmq.svc.cluster.local 5672
Trying 10.0.0.31...
Connected to rabbitmq-2.rabbitmq.rabbitmq.svc.cluster.local.
Escape character is '^]'.
```

Could you suggest an alternative solution, other than manually restarting the node as mentioned in the documentation, or waiting for version 4.0?

_Originally posted by @CrazyMushu in https://github.com/rabbitmq/rabbitmq-server/discussions/8111#discussioncomment-10475666_
