### ISSUE TITLE
HTTP access denied: rabbit_auth_backend_http failed authenticating rabbit: {failed_connect

### ISSUE THREAD

**Issue by thousmile** [rabbitmq/rabbitmq-server#13000]
### Describe the bug

rabbitmq.conf

```conf

auth_backends.1 = http
auth_cache.cached_backend = http
auth_cache.cache_ttl = 15000

auth_http.http_method   = post
auth_http.user_path     = http://data-bridge:18010/rabbitmq/auth/user
auth_http.vhost_path    = http://data-bridge:18010/rabbitmq/auth/vhost
auth_http.resource_path = http://data-bridge:18010/rabbitmq/auth/resource
auth_http.topic_path    = http://data-bridge:18010/rabbitmq/auth/topic
auth_http.request_timeout = 20000
auth_http.connection_timeout = 10000

mqtt.listeners.tcp.default = 1883
mqtt.allow_anonymous  = false
mqtt.vhost            = /
mqtt.exchange         = amq.topic
mqtt.prefetch         = 10

```

use http://data-bridge:18010 There are the following errors

![image](https://github.com/user-attachments/assets/95f20141-e5ba-4814-a7fc-1807f65c4259)

use: http://172.19.0.84:18010 is normal

### Reproduction steps

docker-compose.yml

```
networks:
  app-net1:
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1

services:

  rabbitmq4:
    image: rabbitmq:4.0.5-management
    container_name: rabbitmq4
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=qlm123456
    volumes:
      - ./rabbitmq4/data:/var/lib/rabbitmq/mnesia
      - ./rabbitmq4/logs:/var/log/rabbitmq
      - ./rabbitmq4/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq4/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    networks:
      app-net1:
        ipv4_address: 172.19.0.72
    deploy:
      resources:
        limits:
          memory: 1g

  data-bridge:
    image: bellsoft/liberica-openjre-debian:21.0.5
    container_name: data-bridge
    ports:
      - "18010:18010"
    environment:
      - SPRING_PROFILES_ACTIVE=test
    volumes:
      - ./data-bridge/data-bridge-1.0.1.jar:/app.jar
      - ./data-bridge/application-test.yaml:/config/application-test.yaml
      - ./data-bridge/logs:/logs
      - /etc/localtime:/etc/localtime:ro
    command: java -server -Dfile.encoding=UTF-8 -Duser.timezone=Asia/Shanghai -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    privileged: true
    restart: unless-stopped
    depends_on:
      - rabbitmq4
    networks:
      app-net1:
        ipv4_address: 172.19.0.84
    deploy:
      resources:
        limits:
          memory: 2g


```

1.
2.
3.
...

### Expected behavior

Using Docker service name and IP yields the same result
