### ISSUE TITLE
About Rabbitmq Consumer auto reconnect

### ISSUE THREAD

**Issue by lyl2008dsg** [rabbitmq/rabbitmq-server#1464]
# First of all, thanks to Ribbitmq contribution to open source.
## I had some trouble, hoping to get help, Problem description :
Operations give RabbitMQ expansion,  restart RabbitMQ.
Then  All services are able to produce messages normally.
However, consumer services have not been listen to data.

* Producer    OK
* Consumer  fail

## Version
* RabbitMQ 3.6.5

##
 The way we use it 
```java
@RabbitListener(queues = Queues.RESPONSE_QUEUE, containerFactory="rabbitListenerContainerFactory")
// rabbitListenerContainerFactory is default
```

## configuration
```
listener:
      simple:
        max-concurrency: 1024
        concurrency: 1
        acknowledge-mode: auto
        default-requeue-rejected: false
        retry:
          max-attempts: 3
          enabled: true
          stateless: true
```
