### ISSUE TITLE
Can't stop the app while is starting

### ISSUE THREAD

**Issue by goetas** [rabbitmq/rabbitmq-server#1853]
Thank you for using RabbitMQ and for taking the time to report an
issue.

## Does This Belong to GitHub or RabbitMQ Mailing List?

*Important:* please first read the `CONTRIBUTING.md` document in the
root of this repository. It will help you determine whether your
feedback should be directed to the RabbitMQ mailing list [1] instead.

## Please Help Maintainers and Contributors Help You

In order for the RabbitMQ team to investigate your issue, please provide
**as much as possible** of the following details:

* RabbitMQ version: 3.7.8
* Erlang version: 20.3.8.5
* Operating system, version, and patch level: https://github.com/docker-library/rabbitmq/blob/1a8fd1c6ee027baafb7144c24ad3c995ba5e0d24/3.7/debian/Dockerfile 

Two nodes are in rabbitmq cluster

1) start both nodes, running `docker-compose up -d`:
Docker compose file:
```yml
version: '3.4'
services:
    queue:
      hostname: rabbit-master
      image: rabbitmq:3.7-management
      volumes:
        - queue1_data:/var/lib/rabbitmq
      environment:
        - RABBITMQ_ERLANG_COOKIE=MTEGEJLLJRPSASWUBHFA
      networks:
        default:
            aliases:
              - rabbit-master

    queue-2:
      hostname: rabbit-master-2
      image: rabbitmq:3.7-management
      volumes:
        - queue2_data:/var/lib/rabbitmq
      environment:
        - RABBITMQ_ERLANG_COOKIE=MTEGEJLLJRPSASWUBHFA
      networks:
        default:
            aliases:
              - rabbit-master-2
volumes:
  queue1_data:
  queue2_data:

```
2) login into `queue` ( host `rabbit-master`) and run:
```
rabbitmqctl stop_app
rabbitmqctl join_cluster rabbit@rabbit-maste-2
rabbitmqctl start_app
```
3) remove both containers to simulate a outage (used `docker-compose down`)
4) start only `queue` ( host `rabbit-master`) running `docker-compose up -d queue`.

Rabbit can not start as can not reach `queue-2` ( host `rabbit-master-2`) 
In the logs:
```
queue_1    | 2019-01-29 14:58:41.977 [info] <0.273.0> RabbitMQ hasn't finished starting yet. Waiting for startup to finish before stopping...
queue_1    | 2019-01-29 14:58:58.110 [warning] <0.246.0> Error while waiting for Mnesia tables: {timeout_waiting_for_tables,[rabbit_user,rabbit_user_permission,rabbit_topic_permission,rabbit_vhost,rabbit_durable_route,rabbit_durable_exchange,rabbit_runtime_parameters,rabbit_durable_queue]}
```

5) login into `queue` ( host `rabbit-master`) and run:
```
root@rabbit-master:/# rabbitmqctl force_boot
Forcing boot for Mnesia dir /var/lib/rabbitmq/mnesia/rabbit@rabbit-master
Error: rabbit_running
```

```
root@rabbit-master:/# rabbitmqctl forget_cluster_node rabbit@rabbit-master-2 --offline
Removing node 'rabbit@rabbit-master-2' from cluster
Error: {node_running,'rabbit@rabbit-master'}
```

**Till here everything is as expected.**

6) login into `queue` ( host `rabbit-master`) and run:
```
root@rabbit-master:/# rabbitmqctl stop_app
Stopping rabbit application on node rabbit@rabbit-master ...
Error: unable to perform an operation on node 'rabbit@rabbit-master'. Please see diagnostics information and suggestions below.

Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on http://rabbitmq.com/documentation.html to learn more
 * Consult server logs on node rabbit@rabbit-master

DIAGNOSTICS
===========

attempted to contact: ['rabbit@rabbit-master']

rabbit@rabbit-master:
  * connected to epmd (port 4369) on rabbit-master
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on rabbit-master
  * suggestion: start the node

```

At the same time, in the server logs i have 
```
queue_1    | 2019-01-29 14:58:41.977 [info] <0.273.0> RabbitMQ hasn't finished starting yet. Waiting for startup to finish before stopping...
```

After 10 retries `queue` ( host `rabbit-master`)   exits as expected.

**The question is**:
How to detach the `queue` ( host `rabbit-master`)  node and allow to start the cluster with only that node?
