### ISSUE TITLE
Healthcheck stops responding during mirroring

### ISSUE THREAD

**Issue by mantasaudickas** [rabbitmq/rabbitmq-server#2023]
We have a RabbitMQ cluster with 3 nodes and load balancer on top of it.
Currently there are ~2000 queues on the cluster.
There is a configured policy with settings:
pattern: .*
definition: ha-mode: all; ha-sync-mode: automatic; queue-master-locator: min-masters

For healtcheck at load balancer we configure HTTP check to /api/healthchecks/node

However if one of nodes is restarted and joins a cluster: all nodes stops responding to healthcheck requests and because of this whole cluster becomes unavailable for about a minute.

During investigation we found that nodes starts queue mirroring and for some reason stops responding to HTTP `GET /api/healthchecks/node` requests.

Is this by design or a bug in server?

For now we separated checks for AMPQ to use TCP/IP connection and HTTP check for Management UI, this looks like solving the issue.

For reproducing I use docker cluster: 
docker-compose.yml
```
version: '3'

services:
  rmq1:
    image: rabbitmq:3.7.15-management
    container_name: rmq1
    hostname: rmq1
    networks:
      - rabbitmq
    environment:
      - RABBITMQ_HIPE_COMPILE=0
      - RABBITMQ_ERLANG_COOKIE='rmq'

  rmq2:
    image: rabbitmq:3.7.15-management
    container_name: rmq2
    hostname: rmq2
    networks:
      - rabbitmq
    environment:
      - RABBITMQ_HIPE_COMPILE=0
      - RABBITMQ_ERLANG_COOKIE='rmq'

  rmq3:
    image: rabbitmq:3.7.15-management
    container_name: rmq3
    hostname: rmq3
    networks:
      - rabbitmq
    environment:
      - RABBITMQ_HIPE_COMPILE=0
      - RABBITMQ_ERLANG_COOKIE='rmq'

  haproxy:
    image: haproxy:1.9.8
    container_name: haproxy
    hostname: haproxy
    ports:
      - 15672:15672
      - 5672:5672
      - 1936:1936    
    networks:
      - rabbitmq
    volumes:
    - ./haproxy:/usr/local/etc/haproxy
   

networks:
   rabbitmq:
```

./haproxy/haproxy.cfg file with guest/guest auth:
```
global
    log 127.0.0.1   local0
    log 127.0.0.1   local1 notice
    maxconn 4096
 
defaults
    log     global
    option  tcplog
    option  dontlognull
    timeout connect 6s
    timeout client 60s
    timeout server 60s
 
listen  stats
    bind *:1936
    mode http
    stats enable
    stats hide-version
    stats realm Haproxy\ Statistics
    stats uri /
    
listen rabbitmq
    bind   *:5672
    mode   tcp
    server rmq1 rmq1:5672 check
    server rmq2 rmq2:5672 check
    server rmq3 rmq3:5672 check
    
listen rabbitmq-ui
    bind   *:15672
    mode   http
    option httpchk GET /api/healthchecks/node HTTP/1.0\r\nAuthorization:\ Basic\ Z3Vlc3Q6Z3Vlc3Q=
    http-check expect status 200
    server rmq1 rmq1:15672 check
    server rmq2 rmq2:15672 check
    server rmq3 rmq3:15672 check
```

Init containers:
```
docker-compose up -d

docker exec rmq2 bash -c "rabbitmqctl stop_app"
docker exec rmq2 bash -c "rabbitmqctl join_cluster rabbit@rmq1"
docker exec rmq2 bash -c "rabbitmqctl start_app"

docker exec rmq3 bash -c "rabbitmqctl stop_app"
docker exec rmq3 bash -c "rabbitmqctl join_cluster rabbit@rmq1"
docker exec rmq3 bash -c "rabbitmqctl start_app"
```

I have attached .NET Core console application which creates 3000 queues and starts consumer/publisher:

[src.zip](https://github.com/rabbitmq/rabbitmq-server/files/3256796/src.zip)

When app creates all queues you can restart one container (for example rmq3) and start refreshing page: http://localhost:1936/

It should show how whole rabbitmq-ui group becomes red for a while.
