### ISSUE TITLE
Can't add a new trace

### ISSUE THREAD

**Issue by ysjjovo** [rabbitmq/rabbitmq-server#3854]
Steps to reproduce.
- Setup rabbitmq cluster with tracing plugin enabled.
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: def
  namespace: default
spec:
  image: rabbitmq:3.9.11
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 500m
      memory: 500Mi
  persistence:
    storageClassName: hostpath
    storage: 1Gi
  service:
    type: NodePort
  rabbitmq:
    additionalPlugins:
      - rabbitmq_tracing
```
Then going to management UI,admin tab,tracing menu,input name 'df',last click 'Add trace' button',here is the prompt error messages.
```
Node 'rabbit@definition-server-0.def-nodes.default' could not be contacted: {badrpc,
...
```
But trace log successfully generated in the target file.
```
 kubectl exec def-server-0 -- cat /var/tmp/rabbitmq-tracing/gf.log

Defaulted container "rabbitmq" out of: rabbitmq, setup-container (init)

================================================================================
2021-12-06 8:56:38:529: Message published

Node:         rabbit@def-server-0.def-nodes.default
Connection:   192.168.65.3:48300 -> 10.1.0.100:5672
Virtual host: /
User:         default_user_EtvssC4bIGU7rznNoCy
Channel:      1
Exchange:     logs_topic
Routing keys: [<<"-test.run">>]
Routed queues: []
Properties:   [{<<"content_type">>,longstr,<<"text/plain">>}]
Payload:
^TestSend$
...
```
