### ISSUE TITLE
Disk free limit and memory high water mark "relative" configuration always takes precedence over "absolute" configuration

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/rabbitmq-server#4980]
## Description

The behaviour in configuration key precedence is not consistent for certain configuration keys. Specifically, they configuration key pair `disk_free_limit.relative` + `disk_free_limit.absolute`, and the pair `vm_memory_high_watermark.relative` + `vm_memory_high_watermark.absolute`. The `*.relative` variants seem to take precedence over their `*.absolute` counterparts.

In a setup with a configuration file `rabbitmq.conf` with the key `disk_free_limit.relative = 1.0`, and a configuration file `conf.d/user-configuration.conf` with `disk_free_limit.absolute = 2GB`, I would expect the absolute disk free limit to take precedence, because it was set "later" in the configuration. 

The use case for setting both configuration keys at the same time is to use `rabbitmq.conf` as a "vendor" configuration, or vendor defaults; then let the user customise the configuration via `conf.d/*.conf` files. For other keys, they take precedence when set in `conf.d/*.conf`.

**Comment by michaelklishin** [comment]
Neither was designed to be used in combination with the other.

**Comment by kinoute** [comment]
I encounter the same problem, especially with k8s & Bitnami images as @gtato stated. In this image, there is a default setting `disk_free_limit.relative = 1.0` therefore everything added after that such as `disk_free_limit.absolute = 2GB` is ignored.

**Comment by mleclercq** [comment]
I faced the same issue. As a workaround I set the `RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT` env-var on the rabbitmq container. That env-var is used by the entry-point of the image to set the `disk_free_limit.absolute`.

To do this I added the following to the `RabbitmqCluster` resource:

```yaml
spec:
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              env:
              - name: RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT
                value: 1GB
```
