### ISSUE TITLE
strconv.ParseFloat: parsing "'NaN'

### ISSUE THREAD

**Issue by BillOcsic** [rabbitmq/rabbitmq-server#8738]
### Describe the bug

Getting error:
```
strconv.ParseFloat: parsing "'NaN'": invalid syntax while parsing: "rabbitmq_disk_space_available_bytes 'NaN'"
```

Target state is considered a Down.
Grafana displays nothing.

Looks like issue is with quote.
Running a simple go test case on https://go.dev/play/
```go
package main

import (
	"fmt"
	"strconv"
)

func main() {
	fmt.Println(strconv.ParseFloat("NaN", 64))
	fmt.Println(strconv.ParseFloat("'NaN'", 64))
}
```
returns:
```
NaN <nil>
0 strconv.ParseFloat: parsing "'NaN'": invalid syntax
```

Looks like related to:
https://github.com/rabbitmq/rabbitmq-server/discussions/5143
https://github.com/rabbitmq/rabbitmq-server/discussions/8737

### Reproduction steps

Use a GKE autopilot cluster.
Run a rabbitmq cluster with this configuration file `rabbitmq.config`:
```
[
    { rabbit, [
            { consumer_timeout, 86580000 },
            { loopback_users, [ ] },
            { tcp_listeners, [ 5672 ] },
            { ssl_listeners, [ ] },
            { hipe_compile, false },
            { cluster_partition_handling, pause_minority},
            { vm_memory_high_watermark_paging_ratio, 0.99},
            { disk_free_limit, [{ relative, 1.0}] },
            { collect_statistics_interval, 10000}
    ] },
    { rabbitmq_management, [ { listener, [
            { port, 15672 },
            { ssl, false }
    ] } ] }
].
```
Use a prometheus docker image with this configuration file `prometheus.yml`
```
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
global:
  # This is higher than RabbitMQ's collect_statistics_interval,
  # but still close enough to capture metrics that were refreshed within this interval
  # This value determines the range that we use with rate():
  # https://www.robustperception.io/what-range-should-i-use-with-rate
  scrape_interval: 15s # Default is every 1 minute.
  # scrape_timeout: 10s # Default is 10 seconds.
  # evaluation_interval: 60s # Default is every 1 minute.

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'rabbitmq-server'
    static_configs:
      - targets:
          - '<name-0>.<starefulset>.<namespace>.svc.cluster.local:15692'
          - '<name-1>.<starefulset>.<namespace>.svc.cluster.local:15692'
          - '<name-2>.<starefulset>.<namespace>.svc.cluster.local:15692'
```
Use a graphana docker image with this configuration file:
```
apiVersion: 1

datasources:
   # <string, required> name of the datasource. Required
 - name: prometheus
   # <string, required> datasource type. Required
   type: prometheus
   # <string, required> access mode. direct or proxy. Required
   access: proxy
   # <int> org id. will default to orgId 1 if not specified
   orgId: 1
   # <string> url
   url: http://<prometheus_hostname>.<namespace>.svc.cluster.local:9090
   # <string> database password, if used
   # password:
   # <string> database user, if used
   # user:
   # <string> database name, if used
   # database:
   # <bool> enable/disable basic auth
   # basicAuth:
   # <string> basic auth username
   # basicAuthUser:
   # <string> basic auth password
   # basicAuthPassword:
   # <bool> enable/disable with credentials headers
   # withCredentials:
   # <bool> mark as default datasource. Max one per org
   isDefault: true
   # <map> fields that will be converted to json and stored in json_data
   # jsonData:
   #    graphiteVersion: "1.1"
   #    tlsAuth: true
   #    tlsAuthWithCACert: true
   #    httpHeaderName1: "Authorization"
   # <string> json object of data that will be encrypted.
   # secureJsonData:
   #   tlsCACert: "..."
   #   tlsClientCert: "..."
   #   tlsClientKey: "..."
   #   httpHeaderValue1: "Bearer xf5yhfkpsnmgo"
   version: 1
   # <bool> allow users to edit datasources from the UI.
   editable: false
```

Returned data from endpoint `/metrics` display the line:
```
# TYPE rabbitmq_disk_space_available_bytes gauge
# HELP rabbitmq_disk_space_available_bytes Disk space available in bytes
rabbitmq_disk_space_available_bytes 'NaN'
```

### Expected behavior

Target state should be up, and no issue should be raised if a metrics cannot be computed.
quoted `NaN` should not be returned, the metrics should be disabled.

### Additional context

prometheus:v2.45.0
rabbitmq:3.11.11-management

running in docker
